### ISSUE TITLE
Problem with upstream LXD and storage pools

### ISSUE THREAD

**Issue by jtopjian** [sl1pm4t/terraform-provider-lxd#101]
This issue is to aggregate the discussion happening in a few other PRs in this repo.

A week ago, we began seeing failures in the Travis tests related to storage pools. When this has happened in the past, it was due to too much IO on the dir backend driver, but investigation showed this wasn't the same issue.

@mjrider pinpointed it to a simple:

```
$ lxc storage create foobar dir source=/tmp/foobar
$ lxc storage delete foobar
error: remove /var/lib/lxd/storage-pools/foobar: device or resource busy
```

The problem is detailed here: https://github.com/lxc/lxd/issues/3877

It seems to be unique to Ubuntu 14.04, which is unfortunate since Travis does not support Ubuntu 16.04.

**Comment by jtopjian** [comment]
This problem has been fixed in the upstream LXD code.

So Travis will start working upon the next LXD release. Or we switch to using the snap method of installing LXD.

**Comment by mjrider** [comment]
i think in the long run, snap is going to give more reliable results because how backports and snaps integrate in an old os like trusty

**Comment by jtopjian** [comment]
I'm going to close this. The upstream bug has been fixed and we're going to try installing LXD on Travis via the snap method.
