### ISSUE TITLE
setting privileged=true has no effect

### ISSUE THREAD

**Issue by Remigius2011** [sl1pm4t/terraform-provider-lxd#102]
Hi,

Having experienced getting non-privileged containers even though I have set `privileged=true`, I think this is worth an issue here. Privileged contgainers can currently _only_ be obtained when `security.privileged = true` is set in the container's resource config, i.e.:

    resource "lxd_container" "my-container" {
      name = "my-container"
      image = "some-image"
      privileged = true     # this has no effect!

      config {
        security.privileged = "true"    # this puts the container in privileged mode
      }
    }

I haven't preformed extensive experiments (other than changing the config and seeing the error I experienced going away), but looking at the code in `resource_lxd_container.go`, I haven't found any use of the value of `privileged` that might go into the lxd api requests to create and start the container.

Even though the support for `privileged` might be necessary for backwards compatibility, it may make sense to do the following in order to avoid false expectations (and possibly some headache):

- adjust the documentation
- issue a warning when `privileged` is set with the hint to set `security.privileged` instead

**Comment by jtopjian** [comment]
@Remigius2011 Thanks for reporting this. I think we can easily remedy this so the original `privileged` parameter is still able to be used. I can look into this when I get a moment.

**Comment by Remigius2011** [comment]
Joe, I don't think it is necessary to have this redundancy (i.e. being able to specify privileged mode in two ways). Actually, I personnally prefer to use `security.privileged`, as this is in line with the lxd container configuration and its documentation. But it should be at least clear that `privileged` does not work as expected, i.e. correct the documentation and the samples. If you like, I can try to create a pr for this.

**Comment by jtopjian** [comment]
@Remigius2011 Yes, but we have to keep in mind those who have this plugin already deployed. Simply deleting the privileged parameter might cause configurations to suddenly fail with a syntax error :)

**Comment by jtopjian** [comment]
@Remigius2011 Ah, I misread.

Yes, I understand your point about having two ways of configuring `privileged`. A warning might be the best option since the top-level `privileged` is not used at all.

**Comment by Remigius2011** [comment]
Exactly. Minimal action imho would be to just change the documentation and samples, issue a warning on top of this would make it clear for those who don't read documentations. I'll only tell off-record how much time I spent trying to fix a problem arising from running a non-privileged container but in full confidence the container is privileged...

**Comment by jtopjian** [comment]
Ouch - I do apologize about that.

If you'd like to put a PR together, you are more than welcome to. I'm not sure how familiar you are with Terraform, but the Terraform-ish way of adding the warning message would be similar to here:

https://github.com/terraform-providers/terraform-provider-aws/blob/6cff4f3c51a76b2822db33ae50006ecee4fdaf7f/aws/data_source_aws_iam_role.go#L17-L21

The `Deprecated` field is what should be added to the current top-level `privileged` parameter.

I'd imagine the message would read something like `Set config.security.privileged to 1 instead` or `Use a config setting of security.privileged=1` or something like that.

**Comment by Remigius2011** [comment]
@jtopjian Basically, I could just provide a pr for updating the documentation (which I think is the most important), as I am (still) go illiterate (even though I think I know what's going on when I read the code - and a adding a couple of lines would not intimidate me) and setting up a dev env for go/terraform is currently out of scope - tough I am aware that sooner or later I'll have to touch go anyway. It looks like it's an ideal tool for creating small stand-alone runtimes for any purpose.
