### ISSUE TITLE
Description support

### ISSUE THREAD

**Issue by karlsoon** [sl1pm4t/terraform-provider-lxd#106]
Hello!
Can u please add support for describing? For example, I want to set description to network interfaces like this:
resource "lxd_network" "lxd-internal" {
  name = "lxd-internal"
  description = "Internal network for containers on eth1"
  config {
    ipv4.address = "10.10.100.1/24"
    ipv4.nat     = "false"
    ipv6.address = "none"
    ipv6.nat     = "false"
  }
}

**Comment by jtopjian** [comment]
I think this is possible. Looks like networks have a [description](https://github.com/lxc/lxd/commit/c92ccfd71934c1644ecd22849282dcb2ca682348#diff-04c9e854ea76e15546ab963fea9d85c1) field now.
