### ISSUE TITLE
Idea: Use gox for releases

### ISSUE THREAD

**Issue by jtopjian** [sl1pm4t/terraform-provider-lxd#113]
@sl1pm4t I noticed that the pre-build releases are only for Linux. Mostly for selfish reasons, it'd be nice if there was at least a Darwin release. This is pretty easy to do with gox. See here for an example:

https://github.com/jtopjian/limbo/blob/master/.travis.yml

**Comment by sl1pm4t** [comment]
Hi @jtopjian - yes I've used gox for some company internal providers in the past and it worked well. 
I'll knock up a change.

**Comment by jtopjian** [comment]
Implemented in #119. Thank you again!
