### ISSUE TITLE
Need LXD image datasource

### ISSUE THREAD

**Issue by sl1pm4t** [sl1pm4t/terraform-provider-lxd#12]
Similar to `aws_ami` datasource from Terraform.
I'm working on something, and have some initial code in `f-lxd-image-datasource` branch.
Will merge when finished.

**Comment by shantanugadgil** [comment]
@sl1pm4t Wondering why you closed this? 😢 
I was sort of looking forward to this.
My use case is that I want to know the IP address of eth0 of a particular LXD container, so that I can copy a config file into it (with the IP address as part of the config file).

Regards,
Shantanu
