### ISSUE TITLE
 Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: connect: connection refused

### ISSUE THREAD

**Issue by mrexojo** [sl1pm4t/terraform-provider-lxd#121]
Hi,

We are testing "terraform-provider-lxd", but don't available to launch simple lxc container

- lxc version: 2.21
- /usr/bin/terraform-provider-lxd

main.tf
```
resource "lxd_container" "test1" {
  name      = "test1"
  image     = "ubuntu16"
  ephemeral = false

  config {
    boot.autostart = true
  }

  limits {
    cpu = 2
  }
}
```
terraform plan

Resource actions are indicated with the following symbols:
>  + create

> Terraform will perform the following actions:
> 
>   + lxd_container.test1
>       id:                    <computed>
>       config.%:              "1"
>       config.boot.autostart: "1"
>       ephemeral:             "false"
>       image:                 "ubuntu16"
>       ip_address:            <computed>
>       limits.%:              "1"
>       limits.cpu:            "2"
>       mac_address:           <computed>
>       name:                  "test1"
>       privileged:            "false"
>       profiles.#:            <computed>
>       status:                <computed>
> 
> 
> Plan: 1 to add, 0 to change, 0 to destroy.

terraform apply

> ...
> ..
> Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: connect: connection refused

What's wrong?

**Comment by jtopjian** [comment]
@mrexojo Can you post your `provider` block?

```hcl
provider "lxd" {
 ...
}
```

**Comment by mrexojo** [comment]
Sorry, with the provider

```
provider "lxd" {
}

resource "lxd_container" "test1" {
  name      = "test1"
  image     = "ubuntu16"
  ephemeral = false

  config {
    boot.autostart = true
  }

  limits {
    cpu = 2
  }
}

```

**Comment by sl1pm4t** [comment]
You have an empty provider configuration, which may work if you’re running Terraform on a host where the lxc client has been configured. If not,  you can explicitly define lxd connection details. See the second example in this doc:
https://github.com/sl1pm4t/terraform-provider-lxd/blob/master/docs/README.md

**Comment by rickardrosen** [comment]
Hi @sl1pm4t ,
We have no local configuration and specify scheme = "https" but still the provider fails during apply, trying to connect using a local unix socket.
```
provider "lxd" {
  generate_client_certificates = true
  accept_remote_certificate    = true

  lxd_remote {
    name     = "server-1"
    scheme   = "https"
    address  = "10.x.x.x"
    password = "xxxxxxx"
  }
}
```

TF debug:
```
..."local":config.Remote{Addr:"unix://", Public:false, Protocol:"", AuthType:"", Static:true}
```

However if we create a local lxc config "out of band" and set the "default" connection to be a remote host, it works.

Is this to be expected?

**Comment by sl1pm4t** [comment]
HI @rickardrosen - you can also set one of the lxd_remote's as the default, meaning you shouldn't need to specify in each resource.
e.g.

```
provider "lxd" {
  generate_client_certificates = true
  accept_remote_certificate    = true

  lxd_remote {
    name     = "server-1"
    scheme   = "https"
    address  = "10.x.x.x"
    password = "xxxxxxx"
    default  = true     <<<<<<<<<<<<<<<<<<<<<<
  }
}
```

**Comment by sl1pm4t** [comment]
@mrexojo - did you resolve your issue?

**Comment by sl1pm4t** [comment]
Closing stale issue.
