### ISSUE TITLE
Having problem fetching and building terraform-provider-lxd

### ISSUE THREAD

**Issue by segmond** [sl1pm4t/terraform-provider-lxd#122]
**$** **_go get -v -u github.com/sl1pm4t/terraform-provider-lxd_**
github.com/sl1pm4t/terraform-provider-lxd (download)
github.com/hashicorp/terraform (download)
package context: unrecognized import path "context" (import path does not begin with hostname)

_

> Let's try a different route

_

**$** **_make_**
go build -v
../../hashicorp/terraform/terraform/context.go:4:2: cannot find package "context" in any of:
	/home/segmond/go/src/github.com/hashicorp/terraform/vendor/context (vendor tree)
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/segmond/go/src/context (from $GOPATH)

> Same result

**Comment by jtopjian** [comment]
@segmond You'll need to use Go 1.9 to build the provider.

Let me know if that helps or if you're still having problems.

**Comment by segmond** [comment]
Builds with 1.9 fine.  Thanks
