### ISSUE TITLE
Specifying config volatile.eth0.hwaddr for macvlan triggers rebuild

### ISSUE THREAD

**Issue by MikeStankavich** [sl1pm4t/terraform-provider-lxd#123]
I'm using the following config for secondary IP addresses on an OVH server with macvlan. 
```
  config {
    volatile.eth0.hwaddr = "02:00:00:nn:nn:nn"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
      - nnn.nnn.nnn.nnn/32
    gateway4: nnn.nnn.nnn.nnn
EOF
  }
```
So far I haven't found any way other than this to specify the MAC address assigned by the host. The problem is that when I run an apply, the provider reports that it needs to rebuild the container even though I haven't changed the config. Looks like it doesn't pick up that value when it gets an inventory from LXD.

```
      config.volatile.eth0.hwaddr: "" => "02:00:00:nn:nn:nn" (forces new resource)
```
Is there a better way to specify the mac address from the hosting provider, or some other way to make this work? If not, I can explore making a fix/PR.

Thanks in advance for any assistance or clarification

**Comment by jtopjian** [comment]
@MikeStankavich It looks like we are only setting certain portions of `config`:

https://github.com/sl1pm4t/terraform-provider-lxd/blob/master/lxd/resource_lxd_container.go#L362-L380

and are ignoring `volatile`. Up until now this has been intentional. `volatile` gave off the vibe that the information would be changing and it might have caused unnecessary refreshes or rebuilds.

However, if you're able to _set_ a mac address using `config.volatile`, I wonder if we should look at changing this behavior -- at a minimum, `config.volatile.ethX`.

If you'd like to explore with a patch/PR, go for it. I'd be happy to review.

**Comment by MikeStankavich** [comment]
@jtopjian Thanks for the clarification. I had the same thought about the volatile prefix - seemed like it would be transient and subject to change. But when I looked around upstream in LXD I couldn't find any mention of another way to set a MAC address. I did find a few references to setting volatile.eth0.hwaddr to set a preconfigured MAC address 
https://github.com/lxc/lxd/issues/3694 https://github.com/lxc/lxd/issues/3083 so it seems that's the most known/accepted way of going about it. I'll throw up a quick issue over there and tag this issue just to be sure, but assuming I don't hear otherwise I'll plan to build a PR to pick up volatile.*.hwaddr

**Comment by MikeStankavich** [comment]
As noted opened an issue upstream to confirm that there's not a more correct approach before I start on PR https://github.com/lxc/lxd/issues/4157

**Comment by MikeStankavich** [comment]
Big thanks to Stéphane from LXD for pointing out that is supported to specify hwaddr on a container config device instead of a profile config device. 

So I created a new profile with no network devices and added an inline device block with the hwaddr specified to my container resource definition. It works perfectly!

```
resource "lxd_container" "c1" {
  name =  "c1"
  image = "ubuntu:17.10"
  remote = "h1"
  ephemeral = "false"
  profiles = ["no_nic"]

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:nn:nn:nn"
    }
  }
  config {
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
      - nnn.nnn.nnn.nnn/32
    gateway4: nnn.nnn.nnn.nnn
EOF
  }
}
```

Looks like there's a documentation PR in my future :)

**Comment by jtopjian** [comment]
Nice! Thank you for looking into this :)

**Comment by sl1pm4t** [comment]
Closing this issue as it seems it was resolved.
