### ISSUE TITLE
Unable to attach custom storage volumes to more than one container

### ISSUE THREAD

**Issue by rhass** [sl1pm4t/terraform-provider-lxd#124]
The provider does not seem to allow attaching custom storage volumes to more than a single container even though this is a supported feature.

When running `terraform plan` the following error is returned:
`Error: lxd_volume_container_attach.downloads: resource repeated multiple times`

However running `lxc storage volume attach purehoppiness downloads sonarr /srv/downloads` by hand on the lxc host works fine:

```
$ lxc storage volume list purehoppiness
+--------+-----------+-------------+---------+
|  TYPE  |   NAME    | DESCRIPTION | USED BY |
+--------+-----------+-------------+---------+
| custom | downloads |             | 2       |
+--------+-----------+-------------+---------+
```

**Comment by jtopjian** [comment]
@rhass Can you provide the Terraform configuration (`main.tf` file) you're using to get this error?

**Comment by rhass** [comment]
Ahh! I accidentally had the `lxd_volume_container_attach` assigned the same name. Copy-pasta issue. Sorry! 🤦‍♂️

**Comment by jtopjian** [comment]
@rhass No worries - glad you were able to get it working 😄
