### ISSUE TITLE
Fail to create containers with LXD 3.0.0

### ISSUE THREAD

**Issue by bjonnh** [sl1pm4t/terraform-provider-lxd#126]
lxd_container.test1: failed to create container (test1): Failed container creation: Must specify one of alias, fingerprint or properties for init from image

Using a remote lxd:

resource "lxd_container" "test1" {
  name      = "test1"
  remote = "host-a"
  image     = "ubuntu:"
  ephemeral = false
  profiles  = ["ubuntu_vlanbr2"]
}

**Comment by bjonnh** [comment]
Probably related to: https://github.com/lxc/pylxd/issues/197

**Comment by shantanugadgil** [comment]
@bjonnh 

Which OS is this on? 18.04, I presume?

**Comment by bjonnh** [comment]
Yes 18.04

**Comment by bjonnh** [comment]
It works using the lxd_cache_image. I think I was confused with the image names and repositories.
