### ISSUE TITLE
Please provide a working example

### ISSUE THREAD

**Issue by epronk** [sl1pm4t/terraform-provider-lxd#149]
Please provide a working example.
Below I tried to create a single lxd container based on a centos image.
I'd like to specify 1 or 2 NICs and choose the IP.

When I apply this I get:

> lxd_container.container1: failed to create container (foo): Create container: Create LXC container: Invalid devices: Detect root disk device: No root device could be found

foo.tf:
```
provider "lxd" {
}

resource "lxd_network" "new_default" {
  name = "new_default"

  config {
    ipv4.address = "10.150.19.1/24"
    ipv4.nat     = "true"
    ipv6.address = "fd42:474b:622d:259d::1/64"
    ipv6.nat     = "true"
  }
}

resource "lxd_profile" "profile1" {
  name = "profile1"

  device {
    name = "eth0"
    type = "nic"

    properties {
      nictype = "bridged"
      parent  = "${lxd_network.new_default.name}"
    }
  }
}

resource "lxd_container" "container1" {
  name = "foo"
  image = "centos7"
  ephemeral = false
  profiles  = ["${lxd_profile.profile1.name}"]
}

```

**Comment by jtopjian** [comment]
> Detect root disk device: No root device could be found

There are two possibilities here:

1. Your LXD environment isn't fully configured. Are you able to launch a container using the `lxc` command-line tool?

2. It's possible the profile you're using is not configured with a root device (storage). I suggest doing something like:

```shell
$ lxc profile show default
```

And applying the storage configuration to your `profile` profile.

**Comment by mjrider** [comment]
@jtopjian i can confirm that i'f seen the same error, and your suggestion fixed it

**Comment by jtopjian** [comment]
@mjrider Awesome :) 

Which one fixed the problem? 1 or 2?

**Comment by mjrider** [comment]
sad puppy eyes, i should have read better ;-(
it was option 2

here is my somewhat cleaned default profile:

```
resource lxd_profile "default" {
  count       = 2
  name        = "default"
  description = "Default LXD profile"
  remote      = "${format("lxd-hv-%d", count.index + 1)}"

  device {
    name = "eth0"
    type = "nic"

    properties {
      nictype = "bridged"
      parent  = "br2"
    }
  }
  device {
    type = "disk"
    name = "root"
    properties {
      pool = "default"
      path = "/"
    }
  }
}

```

**Comment by jtopjian** [comment]
OK, cool. I don't mind updating our examples to have the storage device entry, but it's odd that our acceptance tests aren't failing.
