### ISSUE TITLE
Move to Go 1.11

### ISSUE THREAD

**Issue by jtopjian** [sl1pm4t/terraform-provider-lxd#153]
The "official" Terraform providers recently had some automated updates done. For example: https://github.com/terraform-providers/terraform-provider-openstack/pull/570.

We should do the same here.

The formatting changes were done with:

```
gofmt -s -w ./lxd
```

**Comment by mjrider** [comment]
shall we add go mod also, so we have dependency pinning, way to often terraform broke the build with master

**Comment by jtopjian** [comment]
That's the exact reason why we don't vendor :)

There isn't a lot of activity with this provider, so not vendoring helps us catch breaking things easier.

**Comment by jtopjian** [comment]
Implemented in #188
