### ISSUE TITLE
Terraform Upgrade v0.12.0 not working with current LXD plugin. 

### ISSUE THREAD

**Issue by elbrinke** [sl1pm4t/terraform-provider-lxd#162]
Hi, 

We upgraded to Terraform v0.12.0 and found the following error when trying to use the LXD plugin. With v.0.11 it worked fine. 

> Error: failed to load provider "lxd": Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

Would you kindly assist us with this issue. 

Kind Regards
Eddy

**Comment by HSBawa** [comment]
Just curious if you tried `terraform 0.12upgrade`.
https://www.terraform.io/upgrade-guides/0-12.html

**Comment by jtopjian** [comment]
The core issue is that this provider needs to be recompiled and released for Terraform v0.12. This is something we'll have available shortly.

**Comment by HSBawa** [comment]
@jtopjian are you releasing binaries?

**Comment by jtopjian** [comment]
There should have been binaries build upon the last release: https://github.com/sl1pm4t/terraform-provider-lxd/releases/tag/v1.2.0

@sl1pm4t maybe something didn't trigger?

**Comment by sl1pm4t** [comment]
@jtopjian - there was some new / unexpected flakiness in the unit tests that prevented the Travis build from releasing the new binaries. 
https://travis-ci.org/sl1pm4t/terraform-provider-lxd/builds/543103085

**Comment by jtopjian** [comment]
@sl1pm4t Thanks for looking into this. It looks like we've got one test still failing: 

* https://travis-ci.org/sl1pm4t/terraform-provider-lxd/jobs/543103088#L1782-L1783
* https://travis-ci.org/sl1pm4t/terraform-provider-lxd/jobs/543103089#L1229-L1230 

Which is really strange.

**Comment by jtopjian** [comment]
This appears to be some kind of timing issue. Sometimes lxd is attaching the networks to the container in the opposite order. I'll continue to look into this as I have time.

**Comment by jtopjian** [comment]
Looks like now there was an issue with compiling the windows binary?

**Comment by jtopjian** [comment]
@sl1pm4t Thank you for your help!

For posterity, we have temporarily disabled Windows builds until someone can find the time to look into why we're getting compilation errors.

Binaries are now available here: https://github.com/sl1pm4t/terraform-provider-lxd/releases/tag/v1.2.0

I'm going to close this issue.
