### ISSUE TITLE
After Running `lxd init` again I can't connect to the client

### ISSUE THREAD

**Issue by surfer190** [sl1pm4t/terraform-provider-lxd#167]
I get 

`Error: Unable to create client for remote [lxd-server-1]: Could not get remote certificate: Get https://192.168.33.10:8443: EOF`

after running `lxd init` again on the server due to there not being a default storage pool or root device:

```
    Error: failed to create container (ubuntu-web): Failed container creation: Create LXC container: Invalid devices: Detect root disk device: No root device could be found

    on lxd.tf line 38, in resource "lxd_container" "ubuntu-web":
    38: resource "lxd_container" "ubuntu-web" {

    Error: failed to create container (ubuntu-db): Failed container creation: No storage pool found. Please create a new storage pool

    on lxd.tf line 63, in resource "lxd_container" "ubuntu-db":
    63: resource "lxd_container" "ubuntu-db" {
```

**Comment by jtopjian** [comment]
This makes sense to me, as `lxd init` configures/reconfigures an LXD server as new, right? What is the outcome you're looking for in this situation?

**Comment by surfer190** [comment]
Hmmm, are you taking about the storage pool? Why would terraform  now longer be able to connect to the client? I have deleted `~/.terraform/config`

**Comment by surfer190** [comment]
Oops, I had a tunnel running so I couldn't connect with that ip. My mistake.
