### ISSUE TITLE
Error waiting for container (ubuntu-web) network information: timeout while waiting for state to become 'OK' (last state: 'NOT FOUND', timeout: 3m0s)

### ISSUE THREAD

**Issue by surfer190** [sl1pm4t/terraform-provider-lxd#168]
With the following configuration:

```
provider "lxd" {
  generate_client_certificates = true
  accept_remote_certificate    = true

  lxd_remote {
    name     = "lxd-server-1"
    scheme   = "https"
    address  = "192.168.33.10"
    password = "pass"
    default  = true
  }
}

resource "lxd_container" "ubuntu-web" {
  name      = "ubuntu-web"
  image     = "images:ubuntu/xenial/amd64"
  ephemeral = false

  config = {
    "boot.autostart" = true
  }

  limits = {
    cpu = 1
  }
}
```

I get:

Error waiting for container (ubuntu-web) network information: timeout while waiting for state to become 'OK' (last state: 'NOT FOUND', timeout: 3m0s)

**Comment by surfer190** [comment]
I think this has to do with this setting, which defaults to true:

`wait_for_network = false`

**Comment by surfer190** [comment]
I think this is because I didn't setup the bridge network during `lxd init`

**Comment by thepenguinthatwants** [comment]
Hi!

I for some reason gotten same error but being trying to debug few days without help. Seems like my case wasnt about setting up bridge as I already had that. Do you remember what else did you try?
