### ISSUE TITLE
Cluster: all containers provisioned on same node, per apply

### ISSUE THREAD

**Issue by nihr43** [sl1pm4t/terraform-provider-lxd#175]
I'm using this provider with a 6 node lxd cluster.  When I issue a statement like this in my `resources.tf`:

```
resource "lxd_container" "minio" {
  count     = 6
  name      = "minio-${count.index}"
  image     = "images:alpine/3.10"
  provisioner "local-exec" { command = "scripts/provision_alpine.sh ${self.name}" }
}
```

The result is six new containers running on `one` of my lxd hosts.
The next time I trigger a `create` transaction, those containers will be provisioned on the next host.  (its not the same host every time).

By default, the lxd command line tools will perform "round-robin" on container creation across a cluster, regardless of which host you're running the commands on.

Ideally, we would be able to use this provider to provision `n` containers evenly across a cluster, to make statements like the above worthwhile.

My workaround right now is to use `count = 1`, `terraform apply`, and then bump up the count one transaction at a time.

I've built at `b17e82d`
I'm using `Terraform v0.12.0`
My cluster is on lxd `3.18`

**Comment by nihr43** [comment]
I've verified the behavior isn't any different if i factor out the `count` parameter.

This yields the same result:

```
resource "lxd_container" "test-1" {
  name      = "test-1"
  image     = "images:alpine/3.10"
}

resource "lxd_container" "test-2" {
  name      = "test-2"
  image     = "images:alpine/3.10"
}

resource "lxd_container" "test-3" {
  name      = "test-3"
  image     = "images:alpine/3.10"
}
```

**Comment by jtopjian** [comment]
@nihr43 Thanks for reporting this issue.

This provider hasn't been tested with the LXD clustering feature/API, so it's not surprising that there are issues. If someone gets a chance, we'll look into adding this support.

**Comment by nihr43** [comment]
I poked at this over the weekend.  The REST api has a `POST /1.0/containers/<container_name>?target=<cluster_member>`, but it isn't clear to me how to specify a target through the golang client library for a create operation.
On the standard command line it looks like `lxc launch images:alpine/3.10 test --target=hypervisor-876e`
My thinking is that were this feature available, it should be straightforward to do pseudo-random allocation through terraform syntax, hashing container names or the like.

**Comment by nihr43** [comment]
heres an inefficient though more elegant work-around than provisioning one at a time as i was before.

with `scripts/provision_alpine.sh` defined as a `local-exec`:

```
resource "lxd_container" "test" {
  count     = 3
  name      = "test-${count.index}"
  image     = "alpine/stable"
  provisioner "local-exec" { command = "scripts/provision_alpine.sh ${self.name}" }
}
```

We can use `lxc cluster list` and `shuf` to randomly scatter new containers:

```
#!/bin/sh

instance="$1"
current_node="$(lxc info "$instance" \
                  | awk '/Location: /{print $NF}')"
target_node="$(lxc cluster ls --format json \
                 | jq -r .[].server_name \
                 | shuf -n1)"

# lxd crashes if you attempt a no-op move
[ "$target_node" = "$current_node" ] || {
  printf "\033[0;32mrebalancing %s from %s to %s\033[0m" "$instance" \
                                                         "$current_node" \
                                                         "$target_node"
  lxc stop "$instance"
  lxc mv "$instance" --target="$target_node"
  lxc start "$instance"
}
```

**Comment by nihr43** [comment]
I'm on lxd `3.22` now and containers seem to be getting distributed evenly with no workarounds.
