### ISSUE TITLE
Problems with Static Addresses in LXD 3.18

### ISSUE THREAD

**Issue by trvon** [sl1pm4t/terraform-provider-lxd#176]
I am having an issue setting a static IP utilizing LXD version 3.18 (on opensuse) . I am trying to find the root of the issue seeing that the provided terrform syntax currently works on LXD version 3.0.3 (ubuntu server).

```
  device {
    name = "eth0"
    type = "nic"

    properties = {
      nictype = "bridged"
      parent  = lxd_network.zone-4.name
      "ipv4.address" = "10.0.40.5"
    }
```

Specifically, when terraform deploys the containers on version 3.18, the containers are assigned random IP's instead of the provided static address. I have attempted to use the 10.0.40.5/24 CIDR notation and terraform returns the error:

> failed to create container (master): Failed container creation: Create container: Invalid devices: Invalid value for device option ipv4.address: Not an IPv4 address: 10.0.0.5/24

Terraform: v0.12.16

**Comment by jtopjian** [comment]
@trvon Are you able to configure a container with a static IP on the command-line? If so, what are the commands that are successful?

**Comment by trvon** [comment]
I can use `lxc config device set master-zone:master eth0 "ipv4.address=10.0.0.5"` to change the IP address and the changes are reflected in the command `lxc config device show master-zone:master` but when I look at the container with lxc list is still shows a randomly assigned IP address. I also tried restarting the container and the same address is shown.

**Comment by jtopjian** [comment]
I'm guessing this is an OVS issue. I just created a new LXD environment (not using OVS) and am able to create a container with a static IP both through Terraform and on the command-line.

**Comment by trvon** [comment]
I'll explore the OVS configuration and report back.

**Comment by trvon** [comment]
There seems to be an error when using OVS with wicked versus Network Manager
