### ISSUE TITLE
Ability to set a static ip for an image?

### ISSUE THREAD

**Issue by thepenguinthatwants** [sl1pm4t/terraform-provider-lxd#179]
Any possibility to add a static ip to the image like

resource "lxd_container" "ubuntu" {
  name      = "ubuntu"
  image     = "ubuntu:18.04"
  ephemeral = false
  profiles  = ["default"]
  ip_address  = "10.62.176.69"
 }

**Comment by thepenguinthatwants** [comment]
Ooh so I failed on that curly bracket. Tho ubuntu image not found.

**Comment by jtopjian** [comment]
A static IP can be configured like so:

```hcl
resource "lxd_container" "container1" {
  name     = "jttest"
  image    = "images:alpine/3.9/amd64"
  profiles = ["default"]

  device {
    name = "eth0"
    type = "nic"

    properties = {
      nictype        = "bridged"
      parent         = "lxdbr0"
      "ipv4.address" = "192.168.244.20"
    }
  }
}
```

I'm going to close this issue, but please let me know if you have any other questions.

**Comment by thepenguinthatwants** [comment]
For some reasons I got 

`Error: Unable to create client for remote [lxd-server-1]: Get https://10.1.1.8:8443/1.0: Unable to connect to: 10.1.1.8:8443`

**Comment by thepenguinthatwants** [comment]
Actually I noticed that the ip's contain 10.62.176 at start and I tried this

`      "ipv4.address" = "10.62.176.55"`

and it worked thanks!! Not sure if I can get ansible to run roles on it but at least this is a good start.
