### ISSUE TITLE
Statically compiled Binary

### ISSUE THREAD

**Issue by zacksiri** [sl1pm4t/terraform-provider-lxd#180]
I'm trying to use this with the alpine linux container (used by hashicorp's github action) and I'm getting this error

```
Error: Failed to instantiate provider "lxd" to obtain schema: fork/exec /terraform/terraform.d/plugins/linux_amd64/terraform-provider-lxd_v1.2.0_x4: exec format error
```

So I attempted to recompile the plugin using alpine linux but got this error

```
/github/home/go/src/github.com/sl1pm4t/terraform-provider-lxd/lxd/provider.go:577:29: p.LXDConfig.GetContainerServer undefined (type *"github.com/lxc/lxd/lxc/config".Config has no field or method GetContainerServer)
```

**Comment by zacksiri** [comment]
I just tried this in a ubuntu container getting teh same error.

**Comment by jtopjian** [comment]
@zacksiri What's the exact command you're using when trying to compile?

**Comment by zacksiri** [comment]
@jtopjian I just used this one

```
go get -v -u github.com/sl1pm4t/terraform-provider-lxd
```

**Comment by zacksiri** [comment]
@jtopjian i noticed something strange wit the binary, the file size of the 386 version is the same as the amd64 version is the compiled binary correct? (for version 1.2.0)

**Comment by jtopjian** [comment]
Before running `go get ...`, make sure you're using Go 1.11 or above and with the environment variable `GO111MODULE=on` set.

> i noticed something strange wit the binary, the file size of the 386 version is the same as the amd64 version is the compiled binary correct? (for version 1.2.0)

They're different:

```
-rw-rw-r-- 1 ubuntu ubuntu 15175160 Jun 20  2019 terraform-provider-lxd_v1.2.0_linux_386.zip
-rw-rw-r-- 1 ubuntu ubuntu 15189825 Jun 20  2019 terraform-provider-lxd_v1.2.0_linux_amd64.zip
-rwxrwxr-x 1 ubuntu ubuntu 31308773 Jun 20  2019 terraform-provider-lxd_v1.2.0_x4.386
-rwxrwxr-x 1 ubuntu ubuntu 52710906 Jun 20  2019 terraform-provider-lxd_v1.2.0_x4.amd64
```

**Comment by zacksiri** [comment]
i see... ok I will try again

**Comment by zacksiri** [comment]
@jtopjian getting this error now

```
go get: github.com/sl1pm4t/terraform-provider-lxd@v1.2.0 requires
	github.com/flosch/pongo2@v0.0.0-20181225140029-79872a7b2769 requires
	github.com/go-check/check@v1.0.0-20180628173108-788fd7840127: invalid pseudo-version: major version without preceding tag must be v0, not v1
```

**Comment by jtopjian** [comment]
I just tried with go 1.12 and everything worked for me. Can you try in a clean container or virtual machine?

**Comment by zacksiri** [comment]
@jtopjian yeah I'm reverting down to go 1.12 now It was on 1.13

**Comment by jtopjian** [comment]
Thanks for the heads-up. I'll test with 1.13 and see if I can determine what the problem is.

**Comment by zacksiri** [comment]
@jtopjian I got this error when running GO111MODULE=on go get -v -u github.com/sl1pm4t/terraform-provider-lxd

```
go get: error loading module requirements
```

**Comment by zacksiri** [comment]
@jtopjian managed to get it to compile but I'm still getting the same error

Error: Failed to instantiate provider "lxd" to obtain schema: fork/exec /terraform/terraform.d/plugins/linux_amd64/terraform-provider-lxd_v1.2.0_x4: exec format error

not sure why.

**Comment by jtopjian** [comment]
Can you provide any further details on how to reproduce this error? What is the Terraform configuration you're trying to apply?

**Comment by zacksiri** [comment]
That's my terraform file

I'm setting the LXD config via ENV Variables
```
terraform {
  backend "remote" {
    hostname = "app.terraform.io"

    workspaces {
      prefix = "pakman-"
    }
  }
}

provider "lxd" {
}

variable "app_name" {
  type    = string
  default = "pakman"
}

variable "app_hostname" {
  type    = string
  default = "pakman"
}

variable "app_version" {
  type = string
}

variable "cpu" {
  type = map

  default = {
    "production" = 1
    "staging"    = 1
  }
}

variable "memory" {
  type = map

  default = {
    "production" = "1GB"
    "staging"    = "1GB"
  }
}

variable "nodes" {
  type = map

  default = {
    "production" = 1
  }
}

resource "lxd_container" "api" {
  count    = var.nodes[terraform.workspace]
  name     = "${var.app_hostname}-${terraform.workspace}-${count.index + 1}"
  image    = "images:alpine/3.11/amd64"
  profiles = ["default"]

  limits = {
    cpu    = var.cpu[terraform.workspace]
    memory = var.memory[terraform.workspace]
  }

  provisioner "local-exec" {
    command = <<EXEC
    lxc exec ${var.app_hostname}-${terraform.workspace}-${count.index + 1} -- sh -c 'echo "inside container"'
    EXEC
  }
}
```

**Comment by zacksiri** [comment]
@jtopjian I figured it out. it was something to do with git lfs I didn't enable git lfs when checking out my code so the binary was not included. the binary i compiled from source inside alpine container worked.

Thx much!

**Comment by jtopjian** [comment]
@zacksiri Glad you got it figured out. Thank you for your patience!
