### ISSUE TITLE
Persistent volume?

### ISSUE THREAD

**Issue by pshirshov** [sl1pm4t/terraform-provider-lxd#183]
I wish some volumes to survive `terraform destroy`. Is there any way to achieve that?

Same applis to `lxd_cached_image` - seems like it's very inefficient to always remove them on destroy event.

Thanks!

**Comment by jtopjian** [comment]
@pshirshov Terraform has a `lifecycle` block that can prevent things from being destroyed:

https://www.terraform.io/docs/configuration/resources.html#lifecycle-lifecycle-customizations

```hcl
resource "lxd_volume" "volume1" {
  name = "myvolume"
  pool = "${lxd_storage_pool.pool1.name}"

  lifecycle {
    prevent_destroy = true
  }
}
```

But this will throw an error when you try to run destroy on an entire file and only want to keep parts of it.

Another option is to define your persistent resources in one directory and your ephemeral resources in another.  You can reference your persistent resources in one of two ways:

1. By statically typing their names.
2. By referencing the other directories state file with Terraform's [local backend](https://www.terraform.io/docs/backends/types/local.html)

For example:

> t1/main.tf

```hcl
variable lxd_pool {
  default = "lxd"
}

resource "lxd_volume" "volume1" {
  name = "myvolume"
  pool = var.lxd_pool
}

output "volume1" {
  value = lxd_volume.volume1.name
}

output "pool" {
  value = var.lxd_pool
}
```

> t2/main.tf

```hcl
data "terraform_remote_state" "foo" {
  backend = "local"

  config = {
    path = "../t1/terraform.tfstate"
  }
}

resource "lxd_container" "container1" {
  name     = "container1"
  image    = "ubuntu"
  profiles = ["default"]

  device {
    name = data.terraform_remote_state.foo.outputs.volume1
    type = "disk"
    properties = {
      path   = "/mnt"
      source = data.terraform_remote_state.foo.outputs.volume1
      pool   = data.terraform_remote_state.foo.outputs.pool
    }
  }
}
```

Please let me know if this helps and/or if you have any other questions.

**Comment by jtopjian** [comment]
I'm going to close this issue, but happy to re-open or discuss further if needed.
