### ISSUE TITLE
Check for certificate too strict.

### ISSUE THREAD

**Issue by mdone-cloudian** [sl1pm4t/terraform-provider-lxd#185]
According to the LXD people over lxc/lxd#6802, the IP in the certificate should not be checked, as it doesn't match their security model. So if I currently (LXD 3.18 or 3.19) I run `lxd init` and use 127.0.0.1 as the LXD's IP, the certificate is generated with another IP. The proposed fix for that issue is to hardcode 127.0.0.1 for all certificates, rendering all invalid if accessed via another IP. The actual error I'm getting is:

```
        * lxd_volume.demo2-node2-cloudian1: 1 error occurred:
        * lxd_volume.demo2-node2-cloudian1: Get https://127.0.0.1:8443/1.0: x509: certificate is valid for 192.168.0.107, 2a01:e0a:407:9810:a7e3:5838:956b:3dd8, not 127.0.0.1
```

**Comment by jtopjian** [comment]
It looks like this behavior was only merged upstream yesterday (https://github.com/lxc/lxd/commit/6fbaeee00292b14d3f23e2e2c2284762c543f5dd). In order for us to take advantage of this, we'll need to update the vendor dependencies and cut a new release.

Hopefully I can get around to doing this within the next week.

**Comment by mdone-cloudian** [comment]
The new one yes, the old one was to generate a certificate with a non-loopback IP even when the configured ip was 127.0.0.1. In that case the cert also failed to verify as pointed in the logs above.

**Comment by jtopjian** [comment]
Beyond updating the LXD libraries to take advantage of the new way certificates are generated, what else do you propose we do?

**Comment by mdone-cloudian** [comment]
https://github.com/lxc/lxd/issues/6802#issuecomment-580250735

> The LXD security model does not rely on the addresses matching so this change to only including the localhost addresses should make this clearer to everyone.

According to LXD's developer, the LXD client library does not check the IPs in the certificates. I'm not sure how they do that, maybe you can ask him to point you to the code.

**Comment by jtopjian** [comment]
I'll take a look at reproducing this when I get some time and see what the best way of resolving it will be.

**Comment by jtopjian** [comment]
@mdone-cloudian I apologize for the delay. I've looked into this and tried to recreate the same kind of environment you've described in https://github.com/lxc/lxd/issues/6802, but I'm unable to reproduce the issue.

The environment was set up as follows:

```
sudo snap install lxd --channel=stable

_lxc="/snap/bin/lxc"
_lxd="/snap/bin/lxd"
sudo $_lxd waitready --timeout 60
sudo /snap/bin/lxd.migrate -yes
sudo ln -s /snap/bin/lxc /usr/bin/

cat <<EOF | sudo lxd init --preseed
config:
  core.https_address: 127.0.0.1:8443
  core.trust_password: true
  core.trust_password: xxxxxxxxxxxxxx

storage_pools:
- name: local
  driver: dir
  config: {}

networks:
- name: lxd-provision
  type: bridge
  config:
    dns.mode: none
    ipv4.nat: "true"
    raw.dnsmasq: |-
      dhcp-ignore-names
      local-ttl=4938790
EOF

sudo $_lxc config set core.https_address [::]
sudo $_lxc storage create default btrfs source=/dev/sdb
sudo $_lxc profile device add default root disk path=/ pool=default
sudo $_lxc network create lxdbr0 ipv6.address=none ipv4.address=192.168.244.1/24 ipv4.nat=true
sudo $_lxc network attach-profile lxdbr0 default eth0
sudo usermod -a -G lxd ubuntu
```

The generated certificate looks like this:

```
X509v3 Subject Alternative Name:
    DNS:lxd-acc-tests, IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1
```

I'm using the stable release from snap, so the patch discussed in https://github.com/lxc/lxd/issues/6802 to only set the IP to localhost must have already been merged and released.

I'm using the following environment variables:

```
export LXD_ADDR=192.168.244.1
export LXD_PORT=8443
export LXD_GENERATE_CLIENT_CERTS=true
export LXD_ACCEPT_SERVER_CERTIFICATE=true
export LXD_SCHEME=https
```

Note the IP address is not listed in the SAN nor does it resolve to `lxd-acc-tests`.

I'm able to launch containers without error using the latest release of this provider - no custom patches were made.

It's very possible that I have not created the environment similar to yours. If you're able to describe how to create an environment where I can reproduce the issue you're seeing, I can look into this issue further.

**Comment by mdone-cloudian** [comment]
I'm using terraform-provider-lxd_v1.2.0, should I upgrade to 1.3.0?

**Comment by jtopjian** [comment]
Sure, you can try that. But if you're still having the same issue, please let me know how to reproduce your environment so I can further troubleshoot.

**Comment by shawnweeks** [comment]
I'm getting the opposite error message on the current stable release from snap 4.1. I didn't pick 127.0.0.1 as the ip address and i used all defaults on a brand new install of Ubuntu 20.04.

`Error: Failed to join cluster: Failed to setup cluster trust: failed to connect to target cluster node: Get "https://10.0.2.17:8443/1.0": x509: certificate is valid for 127.0.0.1, ::1, not 10.0.2.17`

**Comment by jtopjian** [comment]
I'm going to close this issue, but I can re-open this if needed.

**Comment by Teebor-Choka** [comment]
@jtopjian 4 years later and I hit this issue with terraform lxd provider. Any idea what the problem was, please?
