### ISSUE TITLE
[FEATURE REQUEST] publish an image from container

### ISSUE THREAD

**Issue by thebinary** [sl1pm4t/terraform-provider-lxd#198]
I have a case where my infra deployment would benefit from creating multiple containers from a common image with some base provisioning done on it.

It would be easier if I could create a base cached image from a container with some provisioning done on it, and then deploy other containers with that base cached image.

**Comment by sl1pm4t** [comment]
It sounds like packer can do what you need:
https://www.packer.io/docs/builders/lxd

**Comment by thebinary** [comment]
I still think it might be useful in cases of intermediately required images for a project. so that the complete infrastructure could be built, planned and destroyed with terraform itself.

**Comment by jtopjian** [comment]
I agree with @sl1pm4t in that this is best implemented with Packer.

While this is something that Terraform could possibly do, it's probably not the best way of implementing Terraform. Terraform is best used to "apply" a defined set of infrastructure and maintain state of that infrastructure - not necessarily implementing workflows or processes.

HashiCorp's official workflow includes using Packer to create base/golden images and then use Terraform to create infrastructure based on those images.

I'm not saying this is perfect and not saying that your feature request isn't valid - it's just that implementing it might be going against what Terraform is "supposed" to do and could open the door to additional non-recommended use-cases also being added to this provider.

**Comment by thebinary** [comment]
Yes I do agree. Thank you @sl1pm4t and @jtopjian

**Comment by jtopjian** [comment]
I'm going to close this issue, but happy to discuss this further.
