### ISSUE TITLE
This provider is not supported on terraform version 13?

### ISSUE THREAD

**Issue by thepenguinthatwants** [sl1pm4t/terraform-provider-lxd#208]
Hi guys!

After debugging a bit I've noticed that starting from 0.13 version of terraform I cant use this provider.
Is this a known issue?

**Comment by jtopjian** [comment]
@thepenguinthatwants Yes, please see #203. It also contains a workaround for the time being. @sl1pm4t is working on the steps needed to resolve this when he has time.

I'm going to close this in favor of #203 but let me know if you have any questions.
