### ISSUE TITLE
Error when trying to compile binary

### ISSUE THREAD

**Issue by BaldwinKoo** [sl1pm4t/terraform-provider-lxd#23]
```
go get github.com/sl1pm4t/terraform-provider-lxd

# github.com/sl1pm4t/terraform-provider-lxd/lxd
go/src/github.com/sl1pm4t/terraform-provider-lxd/lxd/resource_lxd_container.go:129: undefined: lxd.Response
go/src/github.com/sl1pm4t/terraform-provider-lxd/lxd/resource_lxd_container.go:208: undefined: shared.BriefContainerInfo
go/src/github.com/sl1pm4t/terraform-provider-lxd/lxd/shared.go:23: undefined: shared.Devices
```

**Comment by jtopjian** [comment]
Can you check and see if you have the `github.com/lxc/lxd` library installed?

```
go get github.com/lxc/lxd
```

**Comment by BaldwinKoo** [comment]
It is indeed installed with terraform 8.1. Currently just using the precompiled binary to test things out.

**Comment by jtopjian** [comment]
How strange... I'm unable to reproduce this.

What command are you using to compile the binary? I'm doing:

```shell
$ cd ~/go/src/github.com/sl1pm4t/terraform-provider-lxd
$ go build .
```

**Comment by BaldwinKoo** [comment]
Im using: `go get github.com/sl1pm4t/terraform-provider-lxd`

Tried it your way and I am getting the exact same error.

Also tried it in a new vagrant env and am getting the same error. 

I am using Ubuntu 16.04.

**Comment by jtopjian** [comment]
Ugh. Duh. I'm really sorry. I just updated the lxd library to the latest commit and I can reproduce this.

It looks like there have been some upstream changes in `github.com/lxc/lxd`... things got moved around.

For now, you can try the following:

```shell
$ cd ~/go/src/github.com/lxc/lxd
$ git checkout 2e194c7fb771cc4948bc20871e77db72c741c00c
```

That's what the latest binaries are built with.

We'll get this updated ASAP.

**Comment by BaldwinKoo** [comment]
Yup that allowed me to compile the binary 👍

**Comment by brandonlamb** [comment]
👍 i got here from a little google searching. i would suggest adding the go commands and steps under an install section of the README, I had no idea how to install this or how the go stuff worked really. A mention of creating a `~/.terraformrc` with a provider block may help new users.

Great project btw, I'm using LXD on bare metal to spin up a few persistent containers using terraform and ansible and then about to launch kubernetes on top with docker.

Definitely seeing some enhancements that could be useful such as if a container or profile already exists, doing something about it

**Comment by sl1pm4t** [comment]
> Definitely seeing some enhancements that could be useful such as if a container or profile already exists, doing something about it.

Could you please elaborate on what you mean @brandonlamb ?
