### ISSUE TITLE
use the URL when remote is specified

### ISSUE THREAD

**Issue by shantanugadgil** [sl1pm4t/terraform-provider-lxd#24]
Hi,
I have a workflow where I have a bunch of containers on a remote lxd.
The remote LXD is a VM on a Proxmox Host.
The IP address of the remote lxd can change over time as it is assigned via DHCP.

I have a "data.external" in place which queries the VM HOST and gets the current IP address of the VM
and updates the local information of the lxc remote 

**Example:**
```

+-----------------+------------------------------------------+---------------+--------+--------+
|      NAME       |                   URL                    |   PROTOCOL    | PUBLIC | STATIC |
+-----------------+------------------------------------------+---------------+--------+--------+
| images          | https://images.linuxcontainers.org       | simplestreams | YES    | NO     |
+-----------------+------------------------------------------+---------------+--------+--------+
| local (default) | unix://                                  | lxd           | NO     | YES    |
+-----------------+------------------------------------------+---------------+--------+--------+
| lxdhost-dummy1  | https://192.168.56.124:8443              | lxd           | NO     | NO     |
+-----------------+------------------------------------------+---------------+--------+--------+

```

I browsed through code and saw that the "daemon_addr" is always generated using "address" and "port"

Would it be possible to use the URL of the "remote" as-is if the field "remote" is specified in the provider.

_The other thing I have tried is to use the provider keys as the interpolated output of the external script, but that doesn't work._

Regards,
Shantanu

**Comment by shantanugadgil** [comment]
<bump>

@sl1pm4t

**Comment by yobert** [comment]
@shantanugadgil I think the best way to fix this would be to use DNS. Is that possible?

**Comment by sl1pm4t** [comment]
Hi. Does the new provider changes in pr #30 help solve your use case?

**Comment by shantanugadgil** [comment]
As of version 0.9.4, this works for me, thanks!

My lxd provider configuration is as follows:

```
provider "lxd" {
  scheme                       = "https"
  address                      = "172.16.xx.yy"
  remote                       = "lxdhost-sample"
  remote_password              = "supersecretpassword"
  generate_client_certificates = true
  accept_remote_certificate    = true
}
```

Going ahead, I plan to retrieve the IP address of the remote using some sort of **data** source (or maybe external) but I am waiting for #12 to be done. 😀 

Thanks and Regards,
Shantanu
