### ISSUE TITLE
Handling multiple servers

### ISSUE THREAD

**Issue by yobert** [sl1pm4t/terraform-provider-lxd#27]
So we have a set of 4 identical LXD servers, all set up with unified networking. Is there a way to specify the remote per-container?

If I'm understanding the source right, you can't. So I'm thinking a way to solve this might be for me to add support for this type of configuration:
```
provider "lxd" {
  remotes = [
    {
      name = "remote1"
      scheme  = "https"
      address = "10.1.1.8"
    },
    {
      name = "remote2"
      scheme  = "https"
      address = "10.1.1.9"
    },
    ... etc ...
}

resource "lxd_container" "test1" {
  name      = "test1"
  image     = "ubuntu"
  ephemeral = false
  remote    = "remote1"
}
```

It could assume the remote name if only 1 was specified, so it would stay compatible.

**Comment by jtopjian** [comment]
Terraform supports multiple providers of the same type:

https://www.terraform.io/docs/configuration/providers.html

Instead of specifying multiple remotes in one provider, try creating a separate provider for each remote and then using the `alias` keyword in the resources.

**Comment by yobert** [comment]
Awesome! That's a much better solution! Thanks!
