### ISSUE TITLE
lxd_cached_image and remote name problem

### ISSUE THREAD

**Issue by shantanugadgil** [sl1pm4t/terraform-provider-lxd#46]
Hi,

The versions I am using are:
### terraform version
Terraform v0.9.3

### terraform-provider-lxd
0.9.4

I have three machines in this setup, for simplicity I'll call them
* driver (this will have remotes pointing to all the lxdhosts) Ubuntu 16.04.2
* lxdregistry (this only acts as an image source) Ubuntu 16.04.2
* lxdhost (over time I will have may lxdhosts) Ubuntu 16.04.2

My Terraform scripts reside  on the **driver** machine
The **lxdhost** machine has been enabled to fetch from the **lxdregistry** (I have tested this manually)

My single .tf file (on the **driver** machine) looks like:

```
provider "lxd" {
  scheme                       = "https"
  address                      = "172.16.xx.yy"
  remote                       = "lxdhost-sample"
  remote_password              = "supersecretpassword"
  generate_client_certificates = true
  accept_remote_certificate    = true
}

resource "lxd_cached_image" "trusty" {
  source_remote = "lxdregistry"
  source_image  = "ubuntu-2017-04-15-01-02-54"
  copy_aliases  = true
}

resource "lxd_container" "test3" {
  name      = "test3"
  image     = "${lxd_cached_image.trusty.fingerprint}"
  ephemeral = false
}
```

When I execute "terraform plan" things are fine:
```
+ lxd_cached_image.trusty
    architecture:     "<computed>"
    copied_aliases.#: "<computed>"
    copy_aliases:     "true"
    created_at:       "<computed>"
    fingerprint:      "<computed>"
    source_image:     "ubuntu-2017-04-15-01-02-54"
    source_remote:    "lxdregistry"

+ lxd_container.test3
    ephemeral:   "false"
    image:       "${lxd_cached_image.trusty.fingerprint}"
    ip_address:  "<computed>"
    mac_address: "<computed>"
    name:        "test3"
    privileged:  "false"
    status:      "<computed>"

```

But, when I do "terraform apply", I get:

```
# terraform apply
lxd_cached_image.trusty: Creating...
  architecture:     "" => "<computed>"
  copied_aliases.#: "" => "<computed>"
  copy_aliases:     "" => "true"
  created_at:       "" => "<computed>"
  fingerprint:      "" => "<computed>"
  source_image:     "" => "ubuntu-2017-04-15-01-02-54"
  source_remote:    "" => "lxdregistry"
Error applying plan:

1 error(s) occurred:

* lxd_cached_image.trusty: 1 error(s) occurred:

* lxd_cached_image.trusty: unknown remote name: "lxdregistry"

```

If I manually execute the following on my **lxdhost-sample**, it works:
`# lxc image copy lxdregistry:ubuntu-2017-04-15-01-05-08 local: --copy-aliases`

Q: What configuration would I have to use to make **lxdhost-sample** pull from **lxdregistry** successfully?

Thanks and Regards,
Shantanu

**Comment by sl1pm4t** [comment]
Hi @shantanugadgil 
Yes, this is a known issue. Currently the provider does not read the remotes configured in the lxc config, and therefore they cannot be referenced.
As mentioned in the README.md, the only LXD remotes that can be used currently are `images`, `ubuntu`, `ubuntu-daily` and the remote defined in the Provider.
I'm working on adding support in the provider to:
- read all the remotes defined in the lxc config
- define multiple remotes in the provider (which will allow running Terraform on systems that don't have lxc installed)

**Comment by jtopjian** [comment]
At first I didn't like the idea of having the provider be able to support multiple non-default remotes. However, it makes a lot of sense when you treat an LXD provider like an LXD client.

For the provider to support multiple remotes, I think it might be best to refactor the provider schema. Instead of:

```hcl
provider "lxd" {
  scheme                       = "https"
  address                      = "172.16.xx.yy"
  remote                       = "lxdhost-sample"
  remote_password              = "supersecretpassword"
  generate_client_certificates = true
  accept_remote_certificate    = true
}
```

something like:

```hcl
provider "lxd" {
  generate_client_certificates = true
  accept_remote_certificate    = true

  remote {
    name            = "lxdhost-sample"
    scheme          = "https"
    address         = "172.16.xx.yy"
    remote_password = "supersecretpassword"
  }
}
```

**Comment by sl1pm4t** [comment]
@jtopjian - this is pretty much what I have in mind. 👍

**Comment by sl1pm4t** [comment]
I'll open a PR soon.

**Comment by sl1pm4t** [comment]
@shantanugadgil not sure if you spotted release v0.9.5beta1 yet and had a chance to try it out? 
It should resolve this issue.

**Comment by shantanugadgil** [comment]
I did test this, but only briefly, haven't had time to thoroughly verify what is working and what is not.
I have three machines for testing from where I run Terraform:
1.  a vanilla CentOS 7 (no LXD installed)
2. CentOS 7 with LXD installed from (https://gist.github.com/AdamIsrael/e6b4a540233a7be6d28decd917b60c3d)
3. Ubuntu 16.04.2

In my brief testing, using the Ubuntu 16.04 as the "driver" machine worked.
Both the CentOS machines couldn't go past the "plan+apply" phase.

I hope I can try this out again soon.

**Comment by shantanugadgil** [comment]
Hi,
I have verified this to work from all three machines as "submitter" hosts.
The problem was that I was using a wrong password (for the lxdregistry block) on the newly setup CentOS machines.

On the Ubuntu 16.04 the lxdregistry certificate had been already accepted quite some time ago, and the wrong password was never triggering an error on the Ubuntu 16.04 machine.


The working setup which pulls an image from the lxdregistry and creates 1 lxd from it is as follows:

```
provider "lxd" {
  generate_client_certificates = true
  accept_remote_certificate    = true

  # the lxd registry from which *all* my target machine will pull the image
  lxd_remote {
    name     = "lxdregistry"
    scheme   = "https"
    address  = "lxdregistry.mydomain.com"
    password = "supersecretpassword1"
  }

  # first of many target node, which will pull the image from lxdregistry
  lxd_remote {
    name     = "mylxdtarget"
    scheme   = "https"
    address  = "172.16.xxx.yyy"
    password = "supersecretpassword2"
  }
}

resource "lxd_cached_image" "mybaseimage" {
  remote        = "mylxdtarget"
  source_remote = "lxdregistry"
  source_image  = "centos-7-stock" # this image is stored on lxdregistry
  copy_aliases  = true
}

resource "lxd_container" "from-centos7-vanilla" {
  remote    = "mylxdtarget"
  name      = "from-centos7-vanilla"
  image     = "${lxd_cached_image.mybaseimage.fingerprint}"
  ephemeral = false
  profiles  = ["default-macvlan", "docker"]
}
```

I use the same exact configuration on all three of my test sumbit hosts, only changing the **resource name** **name** parameters to indicate where it was created from, and all three are working:

```
# lxc list
+----------------------+---------+
|         NAME         |  STATE  |
+----------------------+---------+
| from-centos7-lxd     | RUNNING |
+----------------------+---------+
| from-centos7-vanilla | RUNNING |
+----------------------+---------+
| from-ubuntu-1604     | RUNNING |
+----------------------+---------+
```

**Comment by sl1pm4t** [comment]
Great - thanks for the feedback @shantanugadgil.
Are we OK to close this issue now?

**Comment by shantanugadgil** [comment]
Yes, certainly.

One thing to note though.
Somewhere in documentation it would be good to clarify that **one** of **remotes** in the **provider** block is going to be the **source** for the other machines.

I think this would be useful for folks already familiar with the concept of a docker registry!

Regards,
Shantanu

_👍 keep up the awesome work!_
