### ISSUE TITLE
'Monitor in hung' when creating a large batch of LXD container

### ISSUE THREAD

**Issue by shantanugadgil** [sl1pm4t/terraform-provider-lxd#49]
Hi,

The following is not as much a bug report, but more of an observation; for other folks who might try using this.

If I try creating a batch of LXD together (14+), then a few containers (usually 2 or 3) go into a non-recoverable state.

```
Error applying plan:

2 error(s) occurred:

* lxd_container.mylxd1: 1 error(s) occurred:

* lxd_container.mylxd1: Error waiting for container (mylxd1) to become active: Monitor is hung
* lxd_container.mylxd2: 1 error(s) occurred:

* lxd_container.mylxd2: Error waiting for container (mylxd2) to become active: Monitor is hung
...
...
```

Just running apply again doesn't work, it says "container already exists".

My workaround "fix" involves manually deleting the lxd on the target side and then doing an "apply" again from the Terraform side.

Among other things, I think it could also be due to the storage backend (I use simple dir).

Thanks and Regards,
Shantanu

**Comment by sl1pm4t** [comment]
Interesting, thanks. 
It might be a good test to try tweak the Terraform parallelisation arg to a lower value.

**Comment by shantanugadgil** [comment]
OK. Thanks. I'll try it out:
Ref: https://www.terraform.io/docs/commands/apply.html#parallelism-n

**Comment by shantanugadgil** [comment]
@sl1pm4t this works with reduced parallelism.
In my tests, a parallelism of 4-5 worked fine.
Maybe we can add a note in the docs?

Thanks and Regards,
Shantanu
