### ISSUE TITLE
Provide Precompiled Releases

### ISSUE THREAD

**Issue by jtopjian** [sl1pm4t/terraform-provider-lxd#6]
@sl1pm4t Thoughts on this? I'm happy to attempt this, but just wanted your approval before I begin possibly making a bunch of Travis noise :)

**Comment by sl1pm4t** [comment]
Yes, absolutely! Go for it @jtopjian !
What did you have in mind for binary storage? GitHub releases, Bintray or something else?

**Comment by jtopjian** [comment]
The only experience I have with building binaries so far is through Travis and GitHub releases. For the little I've used it, it works quite well. How about we start with that and move elsewhere if needed?

I'm thinking releases will be based on a tag rather than each commit?

**Comment by jtopjian** [comment]
@sl1pm4t here's a working Travis file that builds Terraform plugin releases:

https://github.com/jtopjian/terraform-provisioner-makefile/blob/master/.travis.yml

I was going to mimic this but realized it requires an api key to this repo. IIRC, that's possible by running the `travis setup releases` command as seen [here](https://docs.travis-ci.com/user/deployment/releases/).

When you have time, would you be able to set up that secret key in the `.travis.yml` file?

**Comment by sl1pm4t** [comment]
Hi @jtopjian - thanks for this! Unfortunately I won't be able to set up the Travis secret until next week. I'm travelling for a few days and don't have a laptop with me.

**Comment by jtopjian** [comment]
No rush at all! Safe travels!

**Comment by sl1pm4t** [comment]
Travis yaml has been updated and the binary is uploaded to GH releases.

**Comment by jtopjian** [comment]
Awesome!
