### ISSUE TITLE
uid/gid mapping issues in file block

### ISSUE THREAD

**Issue by jfgibbins** [sl1pm4t/terraform-provider-lxd#69]
When adding a file with uid/gid, file push does not take into account idmap.  For example with following:
    lxc.id_map =
    lxc.id_map = u 0 100000 200
    lxc.id_map = g 0 100000 200
    lxc.id_map = u 200 200 1800
    lxc.id_map = g 200 200 1800
    lxc.id_map = u 2000 102000 63536
    lxc.id_map = g 2000 102000 63536

if you push a file with uid:gid as 0:0, file pushes correctly, shows up on guest as 0:0, and host as 100000:100000

if you push a file with uid:gid as 999:999, shows up on host and guest as 100999:100999

looking through the code and comparing to  lxd/lxc/file.go, I noticed that they have a few other things which I think may help, but as I don't do any programming in go, I'll have to leave to you, but check out following: shared.GetOwnerMode(finfo) seems to be the key to id shift, and pulls in idmap

	if send_file_perms {
			if c.mode == "" || c.uid == -1 || c.gid == -1 {
				finfo, err := f.Stat()
				if err != nil {
					return err
				}

				fMode, fUid, fGid := shared.GetOwnerMode(finfo)
				if err != nil {
					return err
				}

				if c.mode == "" {
					mode = fMode
				}

				if c.uid == -1 {
					uid = fUid
				}

				if c.gid == -1 {
					gid = fGid
				}
			}

**Comment by jtopjian** [comment]
@jfgibbins Thanks for reporting this. I'm not sure if this was an oversight or if it's related to a bunch of [new changes](https://github.com/lxc/lxd/commit/aed82f789992db52d76b27ff04c0dfc3585099bc) that were recently made.

I'll look into this and have it match the functionality of the lxc client.

**Comment by jtopjian** [comment]
@jfgibbins Actually, I just did a quick test to verify and either I'm unable to reproduce the problem or I'm not understanding the problem.

If I do this:

```shell
ubuntu@helpful-haddock:~$ touch a                  
ubuntu@helpful-haddock:~$ ls -l                    
total 0                                            
-rw-rw-r-- 1 ubuntu ubuntu 0 Jun 26 04:59 a        
ubuntu@helpful-haddock:~$ lxc file push a rsyslog/a
```

I see this on the _host_:

```shell
root@helpful-haddock:/var/lib/lxd/storage-pools/default# ls -l containers/rsyslog/rootfs/
total 0                                                                                  
-rw-rw-r-- 1 101000 101000    0 Jun 26 05:00 a                                           
```

And this on the _container_:

```shell
root@rsyslog:~# ls -l /a
-rw-rw-r-- 1 ubuntu ubuntu 0 Jun 26 05:00 /a
root@rsyslog:~# id ubuntu
uid=1000(ubuntu) gid=1000(ubuntu) groups=1000(ubuntu),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),109(netdev),110(lxd)
```

Now, if I do the following in Terraform:

```hcl
resource "lxd_container" "rsyslog" {
  name = "rsyslog"
  image = "ubuntu"
  profiles = ["default"]

  file {
    content = "Hello, World!\n"
    target_file = "/foo"
    uid = "1000"
    gid = "1000"
  }
}
```

I see the same results.

host:

```shell
root@helpful-haddock:/var/lib/lxd/storage-pools/default# ls -l containers/rsyslog/rootfs/foo
-rwxr-xr-x 1 101000 101000 14 Jun 26 05:04 containers/rsyslog/rootfs/foo                    
```

container:

```shell
root@rsyslog:~# ls -l /foo 
-rwxr-xr-x 1 ubuntu ubuntu 14 Jun 26 05:04 /foo
```

So in both cases, the uid/gid from the host to the guest were mapped correctly. Even in Terraform where the uid/gid were explicitly defined with what would be the uid/gid relative to the container (ie: the user only had to specify what the uid/gid would look like inside the container, which is the correct thing to do as the user should not have to know what the uid/gids look like outside of the container).

Am I not reproducing the problem correctly?

**Comment by jfgibbins** [comment]
Did you include an lxc.id_map in your test?  I didn't see that in your example, and in such a case, I've had it work just fine in all cases too, but not when there are IDs that are mapped different relative to the root.

**Comment by jtopjian** [comment]
@jfgibbins I apologize for being dense and possibly doing something wrong, but I'm unable to even launch a container with the mappings you've provided. Here's what I'm trying:

```hcl
resource "lxd_container" "test" {     
  name = "test"                       
  image = "images:ubuntu/xenial/amd64"
  profiles = ["default"]
  privileged = true
  config {
    raw.lxc = <<EOF
lxc.id_map =
lxc.id_map = u 0 100000 100
lxc.id_map = g 0 100000 100
lxc.id_map = u 200 200 1800
lxc.id_map = g 200 200 1800
lxc.id_map = u 2000 102000 63536
lxc.id_map = g 2000 102000 63536
EOF
  }    
}                                     
```

and I get the following error:

```
lxd_container.test: Creating...
  config.%:       "" => "1"
  config.raw.lxc: "" => "lxc.id_map =\nlxc.id_map = u 0 100000 100\nlxc.id_map = g 0 100000 100\nlxc.id_map = u 200 200 1800\nlxc.id_map = g 200 200 1800\nlxc.id_map = u 2000 102000 63536\nlxc.id_map = g 2000 102000 63536\n"
  ephemeral:      "" => "false"
  image:          "" => "images:ubuntu/xenial/amd64"
  ip_address:     "" => "<computed>"
  mac_address:    "" => "<computed>"
  name:           "" => "test"
  privileged:     "" => "false"
  profiles.#:     "" => "1"
  profiles.0:     "" => "default"
  status:         "" => "<computed>"
Error applying plan:

1 error(s) occurred:

* lxd_container.test: 1 error(s) occurred:

* lxd_container.test: failed to start container (test): Failed to run: /usr/bin/lxd forkstart test /var/lib/lxd/containers /var/log/lxd/test/lxc.conf: 

```

If I change my id_map to this, the container can start:

```hcl
resource "lxd_container" "test" {
  name = "test"
  image = "images:ubuntu/xenial/amd64"
  profiles = ["default"]
  config {
    raw.lxc = <<EOF
lxc.id_map =
lxc.id_map = u 0 100000 2000           
lxc.id_map = g 0 100000 2000
lxc.id_map = u 2000 102000 63536
lxc.id_map = g 2000 102000 63536
EOF                                    
  }                                                                      
}
```

So, I destroyed the above and created a new container with the following:

```hcl
resource "lxd_container" "test" {
  name = "test"
  image = "images:ubuntu/xenial/amd64"
  profiles = ["default"]
  config {
    raw.lxc = <<EOF
lxc.id_map =
lxc.id_map = u 0 100000 2000           
lxc.id_map = g 0 100000 2000
lxc.id_map = u 2000 102000 63536
lxc.id_map = g 2000 102000 63536
EOF                                    
  }                                    
                                       
  file {                               
    content = "Hello, World!\n"        
    target_file = "/tmp/foo.txt"       
    uid = 999                          
    gid = 999                          
  }                                    
}
```

And I can see:

```shell
$ ls -l /var/lib/lxd/storage-pools/default/containers/test/rootfs/tmp/
total 4                                                                                   
-rwxr-xr-x 1 100999 100999 14 Jul 19 04:24 foo.txt                                        
$ lxc exec test -- ls -l /tmp                                         
total 4                                                                                   
-rwxr-xr-x 1 999 999 14 Jul 19 04:24 foo.txt                                              
```

And that looks correct to me.

With regard to `shared.GetOwnerMode`, I must have been half-asleep when I looked at it last. The reason it's not implemented in this Terraform provider is because `GetOwnerMode` checks the source _file_ for the original uid and gid:

https://github.com/lxc/lxd/blob/d9e40ccb1008ea4097735a6721e10dbe90ed63fe/shared/util_unix.go

This isn't applicable here because Terraform is not reading a source file. It's requesting file contents which it will write to a file.

Also, from what I can see, `GetOwnerMode` is not doing any type of id mappings.

So I'm not sure where to go from here?

**Comment by jfgibbins** [comment]
I'm half-asleep myself right now, so let me get my cappuccino in me, and I'll take a look at it and write up a copy/paste lxc profile and terraform config you can use.   I'll also pull the most recent terraform and compile, as I know you guys have been doing a lot of work, since @stgraber popped in and talked about the lxc client after I mentioned your project on the lxc/lxd project.

**Comment by jfgibbins** [comment]
I'm going to close this one for now.  With all the changes, it might not be valid anymore.  And my code doesn't use the feature, so I'll have to write up a separate project to test it again.
