### ISSUE TITLE
Port to the new LXD client package

### ISSUE THREAD

**Issue by stgraber** [sl1pm4t/terraform-provider-lxd#70]
Hey there,

We've recently implemented a new LXD client package an are phasing out our old one (client.go).
LXD itself has now been entirely ported onto the new client code and we're planning on completely removing the old one from the tree with LXD 2.16.

The new client package comes with what should be a future proof API design where feature additions won't cause existing users to break and need modifications.

You can find the Go documentation for it here:  http://godoc.org/github.com/lxc/lxd/client

I noticed you're also parsing the LXD command line tool's configuration to get information on the remotes.
To do so with the new package, you should be using: http://godoc.org/github.com/lxc/lxd/lxc/config

Let me know if you have any questions or need help porting. I've ported all of our own tools and it should be reasonably painless. https://github.com/lxc/lxd/pull/3422 should be full of examples on how to do it.

**Comment by sl1pm4t** [comment]
Thanks for the heads up @stgraber - I'll take a look!

**Comment by stgraber** [comment]
The basics to get you started are:
 - Replace "github.com/lxc/lxd" by "github.com/lxc/lxd/client"
 - Add an import for 'lxd_config "github.com/lxc/lxd/lxc/config"'
 - Replace all "*lxd.Client" by "lxd.ContainerServer"
 - Replace all "lxd.Config" by "lxd_config.Config"
 - Replace NewClient(config, name) by config.GetContainerServer(name)

That should get you to the more interesting part of replacing the individual API calls with the new functions. Some are pretty much one to one mappings, some are designed a bit differently.

**Comment by jtopjian** [comment]
@stgraber Echoing Matt, thank you for the heads up. Seriously - very cool that you proactively reached out to let us know of the changes :)

**Comment by jfgibbins** [comment]
Hi @stgraber, glad to see you popped over here to take a look.  I thought you might appreciate the work they've been doing.
