### ISSUE TITLE
Loopback storage pools flap in configuration

### ISSUE THREAD

**Issue by rhass** [sl1pm4t/terraform-provider-lxd#75]
Issue Details
==========
When creating a ZFS pool which uses a loopback file, the initial creation fails when `source` is defined.

```
Error applying plan:

1 error(s) occurred:

* lxd_storage_pool.default: 1 error(s) occurred:

* lxd_storage_pool.default: custom loop file locations are not supported
```

However, subsequent terraform runs fail when the`source` key/value is not present in the config with the error: 
```
Error applying plan:

1 error(s) occurred:

* lxd_storage_pool.default: 1 error(s) occurred:

* lxd_storage_pool.default: the "source" property cannot be changed

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Example Resource which succeeds for initializing a new pool, but later attempts to modify a the pool when making changes:
```
resource "lxd_storage_pool" "default" {
  name   = "default"
  driver = "zfs"

  config = {
    size           = "10GB"
    zfs.clone_copy = true
    zfs.pool_name  = "default"
  }
}
```

Environment Details
===================
- **terraform-provider-lxd version**: `0.9.8`
- **Host OS**: `Ubuntu`
- **Host OS Version**: `16.04`
- **LXD Version**: `2.15-0ubuntu6~ubuntu16.04.1 (via backports)`

**Comment by jtopjian** [comment]
@rhass Thank you for reporting this. Would you be able to provide the exact steps to reproduce this, including creation of the loopback file as well as the Terraform configuration which uses the `source` argument?

**Comment by rhass** [comment]
@jtopjian No problem! I should be able to sanitize a couple sensative resources and put up my terraform, a chef cookbook to create a VM to run all this, and some detailed steps to reproduce -- but it will take me a little time to get it all together.

Since it is getting a little late, I will try to get back to you after tomorrow or possibly later in the week.

Thanks!

**Comment by jtopjian** [comment]
@rhass No problem at all - take your time.

I just want to make sure I can easily reproduce the problem so I can get it fixed faster :smile:

**Comment by rhass** [comment]
I am not sure what your comfort level is with Chef & Test-Kitchen -- so I will try to be as detailed as possible, but feel free to @ mention me you get stuck somewhere in all this or I managed to skip a step.
Also, sorry for the pre-requisites.

1. [Download and Install VirtualBox](https://www.virtualbox.org/wiki/Downloads) -- You can skip this if you already have it installed.
2. [Download and install ChefDK](https://downloads.chef.io/chefdk) (this will get test-kitchen and all the stuff you need to run the cookbook into place.)  -- You can skip this if you already have it installed, but feel free to upgrade too if you want.
3. Clone https://github.com/rhass/lxd_two 
4. From the lxd_two repo, run `kitchen converge` -- this should download an Ubuntu 16.04 vagrant base box, create a VM, and execute the cookbook which will install LXD and configure the REST services.
5. Clone https://github.com/rhass/tf-module-lxd
6. Run `terraform init`
7. Run `terraform apply` -- This should provision everything successfully.
8. Change something... eg: add a new `lxd_containter` resource.
9. Run `terraform apply` again. At this point you should see the error message `custom loop file locations are not supported`.

It should be noted that there may also be another bug in the destroy process as I found it would not always delete the storage pool, but behaved as if it would delete it. The result is that successive `apply` attempts will allow the `source ` parameter (provided the value is consistent with the existing pool) and somewhat make this issue harder to realize. If you wish to recreate the vagrant VM to get a clean state, just run `kitchen destroy` from the `lxd_two` repo and then `kitchen converge` again to provision a new VM.

Let me know if want to screenshare/video or something if this turns into a pita to reproduce on your end.

**Comment by jtopjian** [comment]
@rhass Thank you for providing all of this! I'm familiar with Test Kitchen, but I think I was able to set up everything similarly without it.

For historical reference in this issue: it's just a default environment created with zfs installed and `lxd init` run.

The good news is that you're seeing a core LXD error, not a Terraform error:

https://github.com/lxc/lxd/blob/b97cfd95e7a9458f7f3cc1d77321037ae6b715e1/lxd/storage_zfs_utils.go#L95

**Comment by rhass** [comment]
@jtopjian Omitting the property does work, but only the first time I run `terraform apply`. The issue really is that when I omit the `source` property, the successive `terraform apply` throws `the "source" property cannot be changed`. I suspect this means that we are not capturing the the specific property value in the tfstate when the pool is initially created, so on a successive run it tries to set something different than what already exists which is not allowed by lxd.

**Comment by jtopjian** [comment]
@rhass Yes, you are correct. LXD is sometimes omitting previously-set config options as well as sometimes changing the values of previously-set options. This is causing Terraform to re-send the config options, thus triggering the error.

I've opened #81 to "fix" this. It's not the best fix, but it'll do at the moment. A better long-term solution would be to create Terraform attributes for all [storage config options](https://github.com/lxc/lxd/blob/master/doc/storage.md) and handle each of them in specific ways.

**Comment by jtopjian** [comment]
@rhass This should now be fixed. Thank you again for reporting it! Let me know if you have any questions.

**Comment by rhass** [comment]
Thanks!

**Comment by rhass** [comment]
@jtopjian This issue appears to have come back in v1.1.0 + Terraform 0.11.0. I am not sure what specific version the behavior was reintroduced. I can create a new issue if you prefer, but it seems to be exactly the same as before.

**Comment by rhass** [comment]
@jtopjian I identified `v1.0.0` as the version in which the regression was introduced. 

Note: I do not have sufficient permissions in GitHub to reopen this issue.

**Comment by jtopjian** [comment]
@rhass That's really strange. The storage pool resource hasn't been touched since the last time you reported this issue.

I'll try to reproduce this when I get some time.
