### ISSUE TITLE
need of a 'make deps' in the Makefile

### ISSUE THREAD

**Issue by shantanugadgil** [sl1pm4t/terraform-provider-lxd#78]
@sl1pm4t  @jtopjian 

Today when I just did a "git pull && make dev", it failed with an unknown "lxd.Server" in the file "lxd/provider.go".

I realized that I should have done a "git pull" on the dependent packages. (in this case "github.com/lxc/lxd")

_Opening an issue here instead of a PR, as I am not familiar which is the best Golang way to do a "go get" and "git pull" for all dependent packages_

Regards,
Shantanu

**Comment by jtopjian** [comment]
I haven't come across a `Makefile` which will update git repos of dependent libraries. Any time I've run into this situation, it's been the same as what you saw: the code doesn't compile so I do a manual `git pull` on the dependent library.

**Comment by shantanugadgil** [comment]
Yes, I did see Makefiles from other projects like Nomad, Consul, gobetween, etc. and so wasn't sure what's the "right" way! 😄 

If there is no _specific_ way, just a comment in the Makefile would do for now, I guess. 🤷‍♂️

**Comment by jtopjian** [comment]
gobetween does something I would consider to be unique. It's using vendoring _per-se_, but using a `Makefile` to build the vendor directory. It's the only project I've seen do that.

The HashiCorp projects all use a full-fledged vendor tool to build the `vendor` directory.

This project doesn't use vendoring at all. Matt and I had a discussion about this in the past. The idea is to not vendor the LXD library so we can more quickly see (in Travis) when the LXD library has been updated.

I'll let @sl1pm4t make a call on the best way to document this.

**Comment by jtopjian** [comment]
> I haven't come across a Makefile which will update git repos of dependent libraries.

To clarify: The `Makefile`s I have seen will run "vendor" commands (`govendor`, `godep`, etc) to update the project's `vendor` directory.

I haven't come across a `Makefile` which will do this:

```shell
cd ~/go/src/path/to/dep_1 && git pull
cd ~/go/src/path/to/dep_2 && git pull
cd ~/go/src/path/to/dep_3 && git pull
```

For the Go projects that I am familiar with, if the project does not use a vendor tool, it is up to the dev/user to manually `git pull` all required dependencies. This should be documented, though.

**Comment by shantanugadgil** [comment]
Yes, that's exactly what I had in mind. The "cd and git pull" can be either a comment or an "echo" during the build.
It would definitely help newbies like me!

Regards,
Shantanu

**Comment by sl1pm4t** [comment]
Would 'go get -u -v ./...' have helped in scenario?

**Comment by shantanugadgil** [comment]
Not a Go expert, but what I have observed is `go get -u -v` doesn't do an update, only checks out if absent, right?

I feel doing a `cd` to the appropriate directory and doing a `git pull` is the right thing to do, rather than checking out all deps in the current directory.

I just dunno how to make it automatic! 😄

**Comment by sl1pm4t** [comment]
From `go get` help page:
```
The -u flag instructs get to use the network to update the named packages
and their dependencies.  By default, get uses the network to check out
missing packages but does not use it to look for updates to existing packages.
```

I think you're right though @shantanugadgil, we could use some more info on how to build it from source.
