### ISSUE TITLE
file writes the sha1sum of the 'content' instead of the actual contents into the file

### ISSUE THREAD

**Issue by shantanugadgil** [sl1pm4t/terraform-provider-lxd#82]
Versions:
Submit Host: CentOS 7.3
Terraform: 0.10.2
terraform-provider-lxd: latest master built from sources
LXD Host: Ubuntu 16.04 + LXD 2.16 from xenial backports

Recently I have restarted by Terraform+LXD experiments with the latest versions and hit the following issue:

Many a times the contents of the file are the `sha1sum` of the content string rather than the content itself.

For the following file block:

```hcl
  file {
    content            = " "
    target_file        = "/etc/mysoftware/optional.conf"
    uid                = 0
    gid                = 0
    mode               = "0644"
    create_directories = true
  }
```

... what I get when I cat the file inside the container is:

```
[root@mylxdcontainer]# cat /etc/mysoftware/optional.conf
b858cb282617fb0956d960215c8e84d1ccf909c6
```

This happens to be the same as the following:
```
$ echo -n " " | sha1sum
b858cb282617fb0956d960215c8e84d1ccf909c6 *-
```

This happens even for blocks where the `content` is an interpolated output of ${file()}
This doesn't occur all the time, nor does it happen for all containers/files.
I haven't been able to figure out a pattern as to why this is occurring.

What I did is, I added a dummy file block above this "optional.conf" file block. (to mess up the ordering).
The subsequent plan detected a change in the file block count and the apply wrote out the correct file contents this time.

This behavior has me extremely puzzled.
I create about 8-10 LXD containers in one go, but I forcibly use `parallelism=2`.
I will try to repeat the exercise by doing a single container at one time and see if I can get predictably correct behavior.

Regards,
Shantanu Gadgil

**Comment by jtopjian** [comment]
Yeah, that's _really_ bizarre behavior! Let me know if this issue goes away if you set `parallelism=1`.

**Comment by shantanugadgil** [comment]
Hi @jtopjian , I have conducted my experiments during the day about 6-7 times now using `parallelism=1`.
I haven't hit an issue so far.

At first, I too thought that there was a random corruption, but then when I noticed that the strings were always fixed length, it led me to the sha1sum.
And then _that_ made a little bit more sense than it being a random corruption.

Thanks and Regards,
Shantanu

**Comment by shantanugadgil** [comment]
Hi @jtopjian any thoughts why this would be happening when parallelism is **not** set to 1?

**Comment by shantanugadgil** [comment]
hi, after another round of testing, this is occurring even when I set `parallelism=1`
I am using:
```
Terraform v0.10.5
lxd-provider 0.10.4
```

**Comment by shantanugadgil** [comment]
Versions:
Terraform v0.10.6
lxd plugin: latest from master.

hi @jtopjian 
This is even more pronounced when I use the `splat` syntax for creating arrays of `lxd_container` with `file` blocks inside them.

I get many random instances wherein the file is just an sha1 rather than the actual content.

Unfortunately, I cannot offer anything more than symptoms as occurring on my test setup.
Do let me know if I can set some DEBUG type variable to get more logs/something.

In the meantime, I am thinking of a workaround:
use the `file` provisioner of Terraform core to push file onto the LXD host and then write `null_resource` per `lxd_container` which will do another "lxc push" into the container.

**Comment by jtopjian** [comment]
@shantanugadgil Thanks for the update. Unfortunately I have not been able to reproduce this. I will try to look at it in more detail when I have some time.

**Comment by shantanugadgil** [comment]
hi @jtopjian not to bother, but the `sha1sum` made me remember the following (not sure if it could be related to the issue I am seeing)

https://github.com/sl1pm4t/terraform-provider-lxd/issues/53
https://github.com/sl1pm4t/terraform-provider-lxd/pull/63/files

_It can't be a coincidence that *exactly* the `sha1` of the file gets written to disk, right!? 😮_ 

Cheers,
Shantanu

**Comment by jtopjian** [comment]
@shantanugadgil No, it's not a coincidence. This is where the hash is coming from. But I'm not sure why you are seeing this on random containers. 

Let me know if you find a way to accurately reproduce this problem and I can look into it further. I can also take a look at this when I get some time.

**Comment by jtopjian** [comment]
Unfortunately I haven't had time to look at this specifically. But I recently worked with someone to implement an object storage resource into the Terraform OpenStack provider. It was based largely on the AWS object resource.

Long story short: The AWS object resource specifies a `source` parameter which will read the contents from a source file on the local workstation. This is most likely to prevent _all_ of the problems we've run into here (having to hash the contents, odd bugs with the hash turning into the contents).

When I have some time, I think I am going to redo the LXD `file` parameter to do the same. I'll rip out the hashing stuff and add the ability to provide _both_ contents and source file. This will be a breaking change, but it should sort out the problem you're seeing.

**Comment by shantanugadgil** [comment]
hi @jtopjian thanks for updating.

FWIW ... my entire setup is local. I use ProxMox as my virtualization software.
CentOS 7._latest_ is my "driver" nodes; it hosts terraform and the provider plugin.

**Comment by jtopjian** [comment]
As of #112, the SHA1 sum is no longer being written to the state, so that should resolve this problem. Let me know if you run into any more issues, though.
