### ISSUE TITLE
Count

### ISSUE THREAD

**Issue by jfgibbins** [sl1pm4t/terraform-provider-lxd#83]
Would be really nice to have a count so that I can spin up multiple with one resource, rather than having to create multiple that would each need editing if a change is needed.  Thanks

**Comment by jtopjian** [comment]
@jfgibbins are you talking about being able to specify:

```hcl
resource "lxd_container" "foo" {
  count = 10
  ...
}
```

?

If so, this is supported. `count` is a core feature of Terraform. 

Are you having trouble using it or running into an error?

**Comment by jfgibbins** [comment]
Didn't seem to work when I tried it.  Was thinking it maybe it had to be written in each provider.  But, then, I was attempting it on device, in an attempt to use a type map to pass multiple devices to the resource.  Let me give it another try today on just the lxd_container resource itself.

**Comment by jfgibbins** [comment]
I"m going to close this.  It's not a problem with your provider, but from severe flaws and limitations in terraform itself.

**Comment by jfgibbins** [comment]
I think what I was trying to do was apply count to devices, but that's not a resource, hence terraform hasn't a clue what to do.  My attempt was to create a module and pass parameters, counts, rather than writing a resource for each individual container.  Issue I was hitting was a variable amount of devices per container, and was trying to use count and length of type map.

**Comment by jtopjian** [comment]
Ah, I understand.

When you want to relate an arbitrary amount of options to a resource, that's usually an indication of the options in question now needing to be its own resource. In your case, it would probably work best if there was a dedicated `lxd_device` resource.

If you can provide a sketch / idea of what you were trying to do, we can see if it makes sense to make an `lxd_device` resource.

Another "gotcha" you might have run into is with modules in general. Modules are tempting to use as a place to store repeatable resources (almost like using them as a function), but they have limitation which prevent such usage... _that_ one can be frustrating.

**Comment by jfgibbins** [comment]
Well, might as well list out the entire process, to give you an idea of what I'm doing.  Perhaps you'll see something better.  Currently, I'm using php to write out the tf scripts based on csv files converted from an excel spreadsheet.  Ideally, I'd like to create a module, pas the variables I need.  I specify container name(or base name), a quantity, image, 1+ profiles, 0+ devices(root is part of default profile), user-data(attempt to convert to tpl), network-data(attempt to convert to tpl), As mentioned, php writes out a tf per device, and it works goog, but seems like count and modules can ease the code a bit, and make maintenance and changes more manageable.  Sample below:

resource "lxd_container" "docker" {
  name     = "docker"
  image    = "ubuntu:xenial"
  profiles = ["default"]
#  depends_on = ["lxd_container.puppet"]

  provisioner "local-exec" { command = "lxc exec puppet -- /opt/puppetlabs/puppet/bin/puppet node p                                                                                                                                         urge ${self.name}.greywolfe.local > /dev/null 2>&1" }
  provisioner "remote-exec" {
    inline = [
      "while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; s                                                                                                                                         leep 5; done;",
      "touch /.dockerenv",
    ]
  }

  config = {
    security.nesting = true
    limits.cpu = 4
    raw.lxc = <<EOF
lxc.cgroup.memory.limit_in_bytes = 8G
lxc.cgroup.memory.memsw.limit_in_bytes = 16G
EOF

    user.user-data = <<EOF
#cloud-config
hostname: docker
fqdn: docker.url.local
manage_etc_hosts: true
write_files:
 - path: /etc/puppetlabs/puppet/csr_attributes.yaml
   content: |
     ---
       extension_requests:
         pp_cloudplatform: 'lxd'
         pp_role: 'docker'
         pp_securitypolicy: ''
         pp_cluster: ''
         pp_zone: 'internal'
         pp_environment: 'prod'
         pp_apptier: ''
         pp_network: ''
description: "docker profile"
EOF

    user.network-config = <<EOF
version: 1
config:
 - type: physical
   name: eth0
 - type: nameserver
   address: ['10.255.0.29']
   search: ['url.local', 'url.org']
 - type: vlan
   name: eth0.1000
   vlan_link: eth0
   vlan_id: 1000
   subnets:
    - address: 10.16.0.11/12
      control: auto
      type: static
 - type: vlan
   name: eth0.1200
   vlan_link: eth0
   vlan_id: 1200
   subnets:
    - address: 10.8.0.11/24
      gateway: 10.8.0.254
      control: auto
      type: static
EOF

  }

  device {
    name = "eth0"
    type = "nic"
    properties {
      host_name = "docker"
      parent = "patch"
      hwaddr = "0015:0A08:000B"
      nictype = "bridged"
    }
  }

  device {
    name = "docker01_local"
    type = "disk"
    properties {
      path = "/data/docker/local"
      source = "/data/docker/docker01"
    }
  }

  device {
    name = "docker_shared"
    type = "disk"
    properties {
      path = "/data/docker/shared"
      source = "/data/docker/shared"
    }
  }

}



Start of new module to replace old code:  Currently depends_on seems to be not possible from within a module which is the other issue I have.  I want some containers to only be created after other's have finished loading.

variable "count" {}
variable "container" { type = "map" }
variable "profiles" { type = "list" }

resource lxd_container "container" {
  count    = "${var.count}"
  name     = "${var.count > 1 ? format("${var.container["host"]}%02d", count.index + 1) : var.container["host"]}"
  image    = "${var.container["image"]}"
  profiles = "${var.profiles}"
#  depends_on = ["module.puppet"]
  depends_on = ["null_resource.test"]
}

**Comment by jfgibbins** [comment]
don't ass why stuff got bolded, it was copied from ssh, crazy unix formatting, lol

**Comment by jtopjian** [comment]
The bold format is due to markdown. If you put the code in code-blocks, it should format fine: https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by jfgibbins** [comment]
we have formatting?  oh god no

**Comment by jfgibbins** [comment]
I ideally, going for spinning up 5 docker containers, initialize the  swarm, load a few things, like consul, vault, spin up puppetmaster, which will use vault and consul(rewriting some code to use them as backends), then once that's up, start spinning up the environment, infrastructure servers, tiered web servers, etc.

**Comment by jfgibbins** [comment]
@jtopjian What are your thoughts?

**Comment by jtopjian** [comment]
The code is hard to read, but in general it looks fine. Sure, there's a lot of explicit device declarations, but that might be the way things are. If you're used to using Puppet, you might have run into a similar situation before where the only option was to explicitly write out a bunch of resources.

You could probably abstract some of it into a module, but more than likely you'll end up with a "docker_lxd_container" module instead of a generic/flexible "my_lxd_container" module.

If you're generating your Terraform code using another script or program, one thing that might help is that Terraform also supports straight JSON:

https://www.terraform.io/docs/configuration/syntax.html#json-syntax

It might be easier to programatically build a JSON object/file that contains an arbitrary number of options and resources.

**Comment by jfgibbins** [comment]
Always hated json, looks so sloppy and convoluted, but if I can pass json to a module and get what I want, so be it.  Have to play around for a while and see how to format and pass that on as a variable.  Terraform is rather nice for straight forward stuff, but it sure shows its limits when it has to scale beyond simple configs.

**Comment by jfgibbins** [comment]
And interpolation doesn't work in a variable, so that would be a json for each of the containers, which nulls the effect of even creating a resource w/count.  Unless I'm missing something.

**Comment by jtopjian** [comment]
@jfgibbins Yes - exactly :)

There are certainly warts, bugs, and other issues with working with Terraform and JSON, _but_ generating the JSON can be done using a whole slew of external tools.

Some Terraform users have mentioned [jsonnet](http://jsonnet.org) as something to use to generate complex JSON files. Think of jsonnet as a mini programming language that generates JSON. 

I personally haven't used jsonnet and if I get into a situation where I needed to use it, I'd probably step back and wonder how I got into that situation, but it's been mentioned as a tool used in complex environments.

**Comment by jfgibbins** [comment]
@jtopjian lol, that's how I am with networking.  I go to customer sites, and they're trying to pulling out all these fancy tools and tricks to make something work.  I always have to teach people, that advanced techniques are designed to add functionality and features.  If you have to use them to fix something, then like you said, you need to step back and figure out how you got yourself stuck in the first place.

**Comment by jfgibbins** [comment]
@jtopjian BTW, for the user.* stuff, I'm still debating between using .tpl files, just to give them a try, but the lack of intelligence in them, means having to program to pick the right one and having multiple templates, but probably easier to just use the php to write the user.* settings directly.  Wish .tpl could do something like lxd does with their template files, but then I'd have to learn yet another templating language and I already have a headache. :)

**Comment by jtopjian** [comment]
IMO, if you're already using something to generate the Terraform configuration, just continue using that for all text to make things simple.

Terraform recognizes `\n`, so you can do something like:

```
user.foo = "line 1\nline2"
```

should be interpreted as:

```
line 1
line 2
```

As well, you can use "heredoc":

```
user.foo = <<EOF
line 1
line 2
EOF
```

However, heredoc probably isn't supported in JSON.

**Comment by jfgibbins** [comment]
I can use heredoc within php and still use variable substitution, so probably stick with that.
