### ISSUE TITLE
libacl and Go 1.9 dependencies

### ISSUE THREAD

**Issue by jtopjian** [sl1pm4t/terraform-provider-lxd#85]
A recent change to upstream LXD now requires that `libacl1-dev` is installed in order for `terraform-provider-lxd` to build. 

I've opened an issue at https://github.com/lxc/lxd/issues/3787 to see if libacl is in fact required for applications that consume LXD. If it is required, we'll have to update Travis and the build documentation accordingly.

As well, Terraform core now requires Go 1.9 to build.

**Comment by jtopjian** [comment]
The awesome LXD team fixed the libacl requirement today! So the only change needed for Travis is using Go 1.9.

**Comment by sl1pm4t** [comment]
Closed by #90
