### ISSUE TITLE
profiles and resources

### ISSUE THREAD

**Issue by jfgibbins** [sl1pm4t/terraform-provider-lxd#88]
Just to verify, using a profile that is created by the provider in a resource, should create an implied dependency, shouldn't it?  I've been having some issues where containers are not created because profile doesn't exist, and vice versa, profile will not delete because it's in use.

**Comment by jtopjian** [comment]
In order to create dependencies between resources, you need to refer to the resource. See the [profiles](https://github.com/sl1pm4t/terraform-provider-lxd/blob/master/README.md#profiles) for an example. If you don't refer to the resources in this way, then Terraform will not know the two resources are related and create them out of order.

**Comment by jfgibbins** [comment]
Doing it json. :(  Wouldn't this be equivelent, or is the interpolation that kicks terraform in the you know what to understand?
{
    "resource": {
        "lxd_profile": {
            "zb_micro": {
                "name": "zb_micro",
                "count": "0",
                "config": {
                    "limits.cpu": "1",
                    "limits.cpu.allowance": "25%",
                    "limits.memory": "1GB",
                    "limits.memory.swap": "TRUE"
                }
            }
        }
    }
}

{
    "resource": {
        "lxd_container": {
            "infra": {
                "provisioner": [
                    {
                        "remote-exec": {
                            "inline": [
                                "while [ ! -f /var/lib/cloud/instance/$
                            ],
                            "connection": {
                                "host": "${cidrhost(\"10.20.0.0/24\", $
                            }
                        }
                    }
                ],
                "count": "3",
                "name": "${format(\"infra%02d\", count.index + 1)}",
                "image": "ubuntu:xenial",
                "profiles": [
                    "default",
                    "zb_micro"
                ],

**Comment by jfgibbins** [comment]
It would seem so, fortunately it was a quick and easy fix, but I swear, terraform has a serious case of the stupids sometimes.  Also just using lxd_profile.name works as well, skip the interpolation.

**Comment by jtopjian** [comment]
I'm not entirely sure how interpolation works with JSON :/

If you aren't able to reference `${lxd_profile.foo.name}`, then `depends_on` might also work:

```hcl
resource "lxd_container" "test1" {
  name      = "test1"
  image     = "ubuntu"
  ephemeral = false
  profiles  = ["default", "profile1"]

  depends_on = ["lxd_profile.profile1"]
}
```

(whatever the JSON equivalent would be)

There's no interpolation required by doing that.

Another heads up is if you are creating containers that use profiles created _outside_ of Terraform. Terraform can only manage and organize resources it knows about.
