### ISSUE TITLE
hexadecimal brain twister 

### ISSUE THREAD

**Issue by jfgibbins** [sl1pm4t/terraform-provider-lxd#89]
Currently use the following to generate IP address to be able to use count:

subnet 10.10.0.0/16
host = 11
count = 5
      "address" => '${cidrhost("' . $net[$network]["subnet"] . '", count.index + ' . "$host" . ')}/24',
answer gives me cidrhost("10.10.0.0/16", xx)  10.10.0.11 - 10.10.0.15

so how to do that with mac address, as terraform doesn't seem to comprehend hex very well, in fact, even doing an output of hex numbers addition, gives you an answer in decimal

I've though about just making a massive lookup map of decimal to hex, but let's face it, large table lookups are lame

**Comment by jtopjian** [comment]
You _might_ be able to use the [`format`](https://www.terraform.io/docs/configuration/interpolation.html#format-format-args-) function. That link references the [godoc](https://golang.org/pkg/fmt/) documentation for `fmt`. Terraform's `format` _should_ support the same interpolation as `fmt` does. For example:

https://play.golang.org/p/uQP6ZQH2G9

So maybe try `format` with `%02x`?

**Comment by jfgibbins** [comment]
@jtopjian Perfect.  That's just what I needed  I knew you would have the answer.  :)  Thanks
