### ISSUE TITLE
ip_address returned

### ISSUE THREAD

**Issue by jfgibbins** [sl1pm4t/terraform-provider-lxd#93]
how is the lxd provider determining the ip address of the container to use for connections as well as for saving in the tfstate file?  Most of my containers are multihomed, and inevitably, the provider always chooses the wrong one.  While I can and do set the connection for remote-exec, that information can't be carried over to other resources.

**Comment by jfgibbins** [comment]
Manually setting the ip_address, would be a trade off with having to set connection for remote-exec, so even money, but ideally combined with #21, one of the connections for network-config could be set as "default" for the purposes of the resource.

**Comment by jfgibbins** [comment]
@jtopjian last detected would definitely be a problem on any container doing any sort of containers, like docker or lxd inside a container, though make sure and leave the tag open, for example some may use, eth1, other's like mine, use trunks, so it's actually eth0.1000, at least until I can get cloud-init to do naming on trunks and get it named mgmt...so you'll have that coded and out in the next hour?  ;)

**Comment by jtopjian** [comment]
Right, the idea would be to configure a container like so:

```hcl
resource "lxd_container" "foo" {
  config {
    user.access_network = "eth0.1000"
  }
}
```

Inside the `for` loop I linked to earlier, there would be an extra piece of logic to see if `user.access_network` was defined and if so, set `ip_address` and `mac_address` to what was defined on `eth0.1000`.

The benefit of using `user` is that LXD reserves it for miscellaneous metadata. As well, keeping that data set in the LXD container's metadata makes it agnostic to cloud-init and such, so it would work with any distribution (with or without cloud-init).

The name `access_network` is taken from the same type of implementation I did in the Terraform OpenStack provider. Perhaps for LXD, `access_interface` might be more applicable.

> so you'll have that coded and out in the next hour?

Not quite :) but it should be a pretty easy thing to put in place. I'll try to get to it within the next week.

**Comment by jfgibbins** [comment]
Sounds like just what I need.  As it stands, my docker containers, end up with 4 addresses, public, mgmt, docker0 and docker_gwbridge with some custom source-routing thrown in.  Hopefully I don't ever decide to run docker on a dmz services container, cause then it would be 5 with the private_ip as well.  Yes, I'm a network geek.

**Comment by jfgibbins** [comment]
@jtopjian Just saw that they released an LXD builder for packer a couple days ago.  Going to play with it and test it for a few days while this update is pending.  Initial tests show some promise.
