### ISSUE TITLE
relative path for disk device source

### ISSUE THREAD

**Issue by nikaro** [sl1pm4t/terraform-provider-lxd#96]
Is it possible to user a relative source path for a disk device? I tried with the config below and it does not seem to work (`lxd_container.pg1: failed to start container (pg1): Failed to run: /usr/bin/lxd forkstart pg1 /var/lib/lxd/containers /var/log/lxd/pg1/lxc.conf:`).

```
provider "lxd" {}

resource "lxd_cached_image" "xenial" {
  source_remote = "ubuntu"
  source_image = "xenial"
}

resource "lxd_container" "pg1" {
  name = "pg1"
  image = "${lxd_cached_image.xenial.fingerprint}"
  ephemeral = false

  device {
    name = "shared"
    type = "disk"

    properties {
      source = "."
      path = "/mnt"
    }
  }
}
```

If it is currently not possible, it would be a nice feature to add :-)

**Comment by shantanugadgil** [comment]
I personally wouldn't recommend such a thing.
How about using terraform's variables/mechanism to evaluate "pwd" ?

**Comment by nikaro** [comment]
I didn't know terraform had this mechanism. I used `source = "${path.cwd}"` and it works. Thank you.

**Comment by jtopjian** [comment]
@shantanugadgil Good call. Thank you :)
