### ISSUE TITLE
does not support splat syntax?

### ISSUE THREAD

**Issue by nikaro** [sl1pm4t/terraform-provider-lxd#97]
Hello,

I'm trying to build an Ansible inventory with ouputs and templates. But it seems that splat syntax are not working.

```
$ terraform console
> lxd_container.pg1.ip_address
10.64.249.15
> lxd_container.*.ip_address
Resource 'lxd_container.*' not found for variable 'lxd_container.*.ip_address'
```

Am i doing something wrong or this provider does not permit this?

Thank you.

**Comment by jtopjian** [comment]
This provider supports everything that core Terraform supports. 

I believe you want to do `lxd_container.pg1.*.ip_address`. This is under the assumption that you would have the following:

```hcl
resource "lxd_container" "pg1" {
  count = 10
  ...
}
```

**Comment by nikaro** [comment]
My container has only one IP. Want i want to do is to get IPs (or names) of all containers.

**Comment by jtopjian** [comment]
The "splat" operator is used to gather information across several resources -- for example, 10 containers housed under the `lxd_container.pg1` resource as shown above.

It might be more helpful to understand what you're trying to use the splat operator for?

**Comment by nikaro** [comment]
Hello @jtopjian, here is what i want to do:
* i have 2 container (but maybe more later)
* i want to get their name and IP
* to build dynamically an Ansible inventory

You can see my actuel tf file here : https://git.ubicast.net/nkarolak/ansible_pg_ha/blob/master/lxd.tf

I'm a Terraform beginner so pardon me if what i'm asking sounds stupid (and i'm french, so sorry for my possibly bad english)… :-)

**Comment by jtopjian** [comment]
@nikaro If I understand what you're trying to do, the splat operator cannot be used to access several resources across _multiple_ resource blocks. For example, this will not work:

```hcl
resource "lxd_container" "pg1" {
  name = "pg1"
  ...
}

resource "lxd_container" "pg2" {
  name = "pg2"
  ...
}

output "foo" {
  value = "${lxd_container.*.ip_address}"
}
```

The above is not supported in Terraform at all (not just the LXD provider).

The following will work:

```hcl
resource "lxd_container" "pg1" {
  name = "pg1"
  ...
}

resource "lxd_container" "pg2" {
  name = "pg2"
  ...
}

output "foo" {
  value = [
    "${lxd_container.pg1.ip_address}", 
    "${lxd_container.pg2.ip_address}"
  ] 
}
```

The "Terraform" way of doing the above is:

```hcl
resource "lxd_container" "pg" {
  count = 2
  name = "${format("pg%d", count.index+1)}"
  ...
}

output "foo" {
  value = "${lxd_container.pg.*.ip_address}"
}
```

I hope that helps.

**Comment by nikaro** [comment]
It helps me a lot. Thank you very much :-)
